    Test crawl DOI

In [1]:
import sys
from pathlib import Path
import pandas as pd
from tqdm import tqdm

# Add project root to Python path
PROJECT_ROOT = Path("../").resolve()
sys.path.append(str(PROJECT_ROOT))

from src.config import TRAIN_PATH_STAGE2, TEST_PATH_STAGE2, CRAWLED_ABSTRACT_PATH
from src.utils.utils import load_csv, save_csv
from src.crawler.fallback_crawler import FallbackCrawler

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
print("===== LOAD DATA =====")

train_df = load_csv(TRAIN_PATH_STAGE2)
test_df = load_csv(TEST_PATH_STAGE2)

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

print("\n===== COLUMNS =====")
print("Train columns:", list(train_df.columns))
print("Test columns:", list(test_df.columns))

display(train_df.head(3))
display(test_df.head(3))

===== LOAD DATA =====
Train shape: (2494, 7)
Test shape: (596, 6)

===== COLUMNS =====
Train columns: ['id', 'title', 'venue', 'year', 'authors', 'doi', 'Label']
Test columns: ['id', 'title', 'venue', 'year', 'authors', 'doi']

,id,title,venue,year,authors,doi,Label
0,0,Proceedings 41st International Conference on L...,iclp,2026,Paul Tarau,https://www.semanticscholar.org/paper/f7391104...,1
1,1,Conditionals and Temporal Conditionals for Gra...,iclp,2025,NaN,https://www.semanticscholar.org/paper/8328d53d...,1
2,2,Learning and Contesting Assumption-based Argum...,iclp,2025,"Ofer Arieli, Jesse Heyninck",https://www.semanticscholar.org/paper/1c433ff0...,2

,id,title,venue,year,authors,doi
0,979,Explainable Planning Using Answer Set Programm...,kr,2020,"Van Nguyen, Stylianos Loukas Vasileiou, Tran C...",10.24963/kr.2020/66
1,1106,SOGrounder: Modelling and Solving Second-Order...,kr,2018,NaN,https://www.semanticscholar.org/paper/6968fcf3...
2,1894,Refinement for Structured Concurrent Programs.,cav,2020,NaN,https://www.semanticscholar.org/paper/23da9bfd...

In [3]:
print("===== INIT CRAWLER =====")

crawler = FallbackCrawler(timeout=30)

print("Crawler initialized successfully.")

===== INIT CRAWLER =====
Crawler initialized successfully.

In [4]:
print("===== PREPARE CRAWL STORAGE =====")

crawl_results = []

print("Train size:", len(train_df))
print("Test size:", len(test_df))

sample_doi = train_df.iloc[0]["doi"]
sample_id = train_df.iloc[0]["id"]

print("Sample DOI:", sample_doi)
print("Sample ID:", sample_id)

===== PREPARE CRAWL STORAGE =====
Train size: 2494
Test size: 596
Sample DOI: https://www.semanticscholar.org/paper/f7391104e89d3ae6456960c316a2758d5850e6b0
Sample ID: 0

In [5]:
print("===== MERGE TRAIN + TEST FOR CRAWLING =====")

all_df = pd.concat([train_df, test_df], axis=0)

print("Total to crawl:", len(all_df))

crawl_results = []

for idx, row in tqdm(all_df.iterrows(), total=len(all_df)):

    doi = row.get("doi", "")
    title = row.get("title", "")
    paper_id = row.get("id")

    try:

        result = crawler.fetch_by_doi(
            doi=doi,
            title=title,
            paper_id=paper_id
        )

        if result:
            crawl_results.append(result)

    except Exception as e:

        print(
            f"[ERROR] "
            f"id={paper_id} | "
            f"title={str(title)[:60]} | "
            f"{str(e)}"
        )

print("===== CRAWL DONE =====")
print("Total crawled:", len(crawl_results))

===== MERGE TRAIN + TEST FOR CRAWLING =====
Total to crawl: 3090

  0%|          | 0/3090 [00:00<?, ?it/s]

  0%|          | 1/3090 [00:06<5:46:12,  6.72s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f7391104e89d3ae6456960c316a2758d5850e6b0

  0%|          | 4/3090 [00:19<4:02:42,  4.72s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/666f0fa6242f59f0efad52bf4fca6e57dec3df21

  0%|          | 5/3090 [00:33<7:06:56,  8.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/08195948156fdb7d400d37e1cd8af51fbcd2918b

  0%|          | 7/3090 [00:43<5:32:11,  6.46s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e0033a1ff429de2549c3758e1c5bf8591ecd9c53

  1%|          | 37/3090 [02:51<4:04:10,  4.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7aa66cf8977d670bbcf5f9d9b0c40decbac738da

  1%|▏         | 44/3090 [03:21<4:05:21,  4.83s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/89283796e7011f1e43d87fcf9868c7392c36a79f

  2%|▏         | 48/3090 [03:37<3:45:07,  4.44s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7ebdfcb9f0a43a41a96d6d7954f1046e5aaee1fd

  2%|▏         | 51/3090 [03:54<4:33:47,  5.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5b3d9b60bcc94f216f20e4ffdd4105fdaf28ed87

  2%|▏         | 54/3090 [04:07<4:09:31,  4.93s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f3bbae0294c78f79039c31c39dc5c1c2cfc108a8

  3%|▎         | 88/3090 [06:34<3:48:02,  4.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/491ddddaf4b898429670ffb3182dde86d20d71af

  3%|▎         | 89/3090 [06:42<4:32:29,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0abc223877f00d8dded1163cb92e085708fa8fd3

  3%|▎         | 99/3090 [07:27<3:15:11,  3.92s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3d976acb2104226bcd8a518c7c0fe0322aea6514

  3%|▎         | 100/3090 [07:33<3:40:15,  4.42s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

  3%|▎         | 104/3090 [07:53<4:05:04,  4.92s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b61ad27cdc4725f487da3dd1330e1ee4535ea60f

  3%|▎         | 105/3090 [07:58<4:03:41,  4.90s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1758181a84e48d22d67ae45d4a10061a84126699

  3%|▎         | 108/3090 [08:12<4:05:06,  4.93s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/87145d100bdb1aa8ed2e0c093c04d02007aa5685

  5%|▍         | 153/3090 [11:26<4:18:30,  5.28s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/41d33879286a5db68d67c402186f286acc5aaee6

  5%|▌         | 155/3090 [11:36<4:16:16,  5.24s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f0a5a4aeb665db624d9811fc0cff148475b3d6d6

  5%|▌         | 161/3090 [12:01<3:14:17,  3.98s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/964e72169f184bbd5964b0963164e0ab9df3a088

  6%|▌         | 189/3090 [13:52<3:29:50,  4.34s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/637b35ddf0964769adce84e160e6846ee48a7642

  6%|▋         | 199/3090 [14:35<3:56:07,  4.90s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/552c0d68c29884f2516826802f919fb3e3358668

  7%|▋         | 213/3090 [15:35<3:40:00,  4.59s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/78c2c6e6a9f4ae66e45d71c9467729cc39e10de7

  7%|▋         | 214/3090 [15:41<4:08:06,  5.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0674b876781c37d0f49819d49e7d5b889a8e16ec

  7%|▋         | 215/3090 [15:47<4:13:07,  5.28s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/199e4fa73f240833464ab5f20401822d1199b67d

  7%|▋         | 216/3090 [15:53<4:22:27,  5.48s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/41cfc3b05243c8ef0d877c9e491fad5b0f7fdeb2

  7%|▋         | 220/3090 [16:08<3:33:29,  4.46s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/74be40361f9330b6ba6ff224e199f7f13e228dc0

  7%|▋         | 224/3090 [16:22<2:54:40,  3.66s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/aac4e404ee83f0e217ccbc3a6fdfbb799b2101b8

  7%|▋         | 227/3090 [16:36<3:33:33,  4.48s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/df04a6b99eaf2cd434716fcdd041b0c36a110063

  7%|▋         | 231/3090 [16:51<3:18:01,  4.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/417b30c0e75b13a38b6da68373a577c41c6f1132

  8%|▊         | 233/3090 [17:00<3:33:50,  4.49s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/efc6738cd5c6bd84b3649d61c9b74e002e39e4b3

  8%|▊         | 241/3090 [17:34<3:50:49,  4.86s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/19c1f1bb9ef0ad0c8e8cf6b9fc4ecb517cf50097

  8%|▊         | 251/3090 [18:19<3:52:15,  4.91s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/cbccb52c1754970ecf96f668c0bd289e05ae6510

  8%|▊         | 252/3090 [18:27<4:38:03,  5.88s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2878dfca545478eef14ff01fede7563efeebaa59

  8%|▊         | 255/3090 [18:41<3:57:54,  5.03s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/309f8ff0573d8baf04838f74a407d2b9453d8eec

  8%|▊         | 256/3090 [18:46<4:00:28,  5.09s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d62ee4dec344f18f6d56e3f9902e3a3663e48f33

  8%|▊         | 257/3090 [18:51<3:53:30,  4.95s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9264dd7630f641f581ffd07bec8f1d6575bfe7a1

  8%|▊         | 258/3090 [18:58<4:23:29,  5.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/112d3e13c16f784d1b6ae3bff6c5eafc8acba6c5

  9%|▊         | 263/3090 [19:18<3:30:51,  4.48s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ae18f56b0a2ec9827fc4143ea0e5219286215502

  9%|▊         | 265/3090 [19:26<3:20:21,  4.26s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0650a10cd8d348b95ce0a7fd1469687bfb976041

  9%|▊         | 267/3090 [19:36<3:37:38,  4.63s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3be81ca8c961abc816cd4beff0c76f002a886682

  9%|▊         | 268/3090 [19:42<3:54:39,  4.99s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/874ea93b408de0be9d28ae710f2548732552b82d

  9%|▉         | 271/3090 [19:59<4:20:50,  5.55s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b9768643575fadefaccd22ec0f46519dcd7c3af4

  9%|▉         | 272/3090 [20:03<4:06:17,  5.24s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c3d685d918018b3148c7fc108dd458824eda3f4c

  9%|▉         | 274/3090 [20:14<4:15:55,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/435365a84233571594c4a7a11b1dd248a9316bb0

  9%|▉         | 275/3090 [20:19<4:11:08,  5.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/50af60be82ef745275d8562a752788903c22a8ec

  9%|▉         | 277/3090 [20:27<3:38:45,  4.67s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1d505cad19efa28ccec8c86851a1d925a90404e3

  9%|▉         | 280/3090 [20:37<3:13:42,  4.14s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3b60902c30e4dad53292ee8b3db4db4f017feb2a

  9%|▉         | 281/3090 [20:43<3:32:03,  4.53s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9faafae2b66574153ca719bab70339dfd4fe8b43

  9%|▉         | 288/3090 [21:19<3:46:41,  4.85s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3e1e4834293c2a54be431109f7a7352de4777b6f

 10%|█         | 309/3090 [23:06<4:00:32,  5.19s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f6d0d108d12511c5d998639e3f7632b562cefca8

 10%|█         | 311/3090 [23:14<3:39:44,  4.74s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5ee8e91b4b169130c74a34125514e833a53cfdfa

 10%|█         | 313/3090 [23:25<3:57:43,  5.14s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f01ad535f70351a8a1c59e7757a802eba2bb5e5c

 10%|█         | 314/3090 [23:31<4:07:27,  5.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b48d30c0a4b1e1ecfc97347f312233719d86a267

 10%|█         | 316/3090 [23:40<3:57:08,  5.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/53b11deb157e7d9c6ad6a7d8c06b8eaf6c821c0d

 10%|█         | 317/3090 [23:47<4:15:04,  5.52s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7f5921a1681a0ee53dae5f53ee1b159641c939a1

 10%|█         | 320/3090 [23:59<3:45:13,  4.88s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8e9ad5a621243843830a825a9fec849c4bd3cb3c

 10%|█         | 322/3090 [24:10<4:02:37,  5.26s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/124a0283742e35477cc672bdb60e485bc6a1cf12

 11%|█         | 345/3090 [25:42<3:21:15,  4.40s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/92c1111a2a9c4e8466db05e75a98827c763b9b2b

 13%|█▎        | 398/3090 [29:11<3:21:00,  4.48s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8a96be74934c7aa89609056ab10f2c824b469d0b

 13%|█▎        | 414/3090 [30:05<2:53:57,  3.90s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e71ab024a90d0330fa15d22ef81245c8f47dda3e

 14%|█▍        | 427/3090 [30:49<2:59:53,  4.05s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6b82743625e8fa14a89743f3df494141f0e87715

 14%|█▍        | 429/3090 [30:57<3:07:03,  4.22s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 21%|██        | 642/3090 [50:29<3:26:44,  5.07s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 21%|██        | 644/3090 [50:39<3:35:33,  5.29s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/673829d517c4288e849c764011bdd38181966494

 21%|██        | 645/3090 [50:46<3:50:56,  5.67s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/68551c900ac4cc5571f7bf871b941144b28d6ce2

 21%|██        | 646/3090 [50:51<3:44:37,  5.51s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/33361d49d0d3eacc147f54d296aa60cbf9edf946

 21%|██        | 647/3090 [50:59<4:16:46,  6.31s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0e19cd90639e63aae31163ac5b1f80879b9283d0

 21%|██        | 648/3090 [51:05<4:13:26,  6.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b12fb8873ecc277717d7438543fb4fe85e6a4201

 21%|██        | 649/3090 [51:13<4:24:49,  6.51s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7f36ce3bd2005c89d2c1546744bf68d2fed47173

 22%|██▏       | 675/3090 [53:24<3:11:55,  4.77s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f7540ad28478e46add1869c037470d75be631601

 22%|██▏       | 677/3090 [53:32<2:52:09,  4.28s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 23%|██▎       | 696/3090 [54:58<3:04:43,  4.63s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8d492c15b7deb4c56ba0829d7ee86a05aa185c6b

 24%|██▍       | 739/3090 [58:02<2:46:55,  4.26s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/abef72c3246f15cfd2334021f3c96dc11b2a5222

 27%|██▋       | 834/3090 [1:05:44<3:25:52,  5.48s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4bf76e84698caf268db80eef0e43d6fad955ecce

 27%|██▋       | 836/3090 [1:05:54<3:16:12,  5.22s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/876f0e27c608325c75c6d9d205343795aa1decc6

 27%|██▋       | 848/3090 [1:07:01<3:18:07,  5.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a05ccadffb669bcdf26ae0c29a0bf59bb39bdacd

 28%|██▊       | 852/3090 [1:07:24<3:22:46,  5.44s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/eea1c3b9690104aec060c88f785dd7f9170fa8ab

 28%|██▊       | 853/3090 [1:07:28<3:10:04,  5.10s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 28%|██▊       | 854/3090 [1:07:32<3:01:04,  4.86s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1d517ee6c466ba2ca5eb51f2f116e456299fd4e9

 28%|██▊       | 855/3090 [1:07:37<2:56:37,  4.74s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/36969f2e396a4086adf1cddaf9d60b9d807309d3

 28%|██▊       | 856/3090 [1:07:41<2:54:19,  4.68s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2b130447a61f0f1c8c240756356fafd720e107c7

 28%|██▊       | 857/3090 [1:07:45<2:40:26,  4.31s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/837336ff35e9265d21b45968ae1c33c804f12496

 28%|██▊       | 858/3090 [1:07:48<2:29:36,  4.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/569c2d8843311b79bf8a34aee0f5b8449b46b4ce

 28%|██▊       | 859/3090 [1:07:52<2:31:08,  4.06s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/158da8eaec1582205b6537f38480256f197e32b1

 28%|██▊       | 860/3090 [1:07:57<2:32:34,  4.11s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dafa2aad0a9be3267abc84a2a9f6ba23fc6fdae8

 29%|██▉       | 896/3090 [1:11:12<3:02:32,  4.99s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/316d9e0d3cdc23584190aed3448ba900113a7bdc

 30%|███       | 930/3090 [1:14:40<4:16:49,  7.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e57d5231f97aae78f155a3fa36edd40dae8161a5

 30%|███       | 931/3090 [1:14:45<3:48:22,  6.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/adb3de1bda304577abd87595a4e8d86695189d3f

 30%|███       | 933/3090 [1:14:54<3:13:36,  5.39s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/becd9b3b4b1bd0fd0d0761d650fc08b919f9a421

 30%|███       | 934/3090 [1:14:57<2:56:18,  4.91s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/472ae758b1127b4240fec4dc443ce186272b5ef0

 30%|███       | 936/3090 [1:15:08<3:00:40,  5.03s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8e4d8ad40a9d6ce2197edc99aeda7459afe0a40f

 30%|███       | 937/3090 [1:15:12<2:50:22,  4.75s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7d2e9d5a9e2f85c3775f4aed2b0a3ab2df4a6148

 30%|███       | 938/3090 [1:15:17<2:59:08,  4.99s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/be1059b6146f4cc354a7b9f7fdf5305098828193

 30%|███       | 939/3090 [1:15:22<2:56:27,  4.92s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c6173ba0fd3630b06dcb1028dc7bcdf396697ba5

 30%|███       | 940/3090 [1:15:27<2:52:16,  4.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/75d627aae2307439e8d2d2cb8495489e751d570d

 30%|███       | 942/3090 [1:15:36<2:48:41,  4.71s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4a408509e7ef5aa7aa27349c1eb89d6e741919e3

 31%|███       | 943/3090 [1:15:40<2:40:07,  4.47s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/44dc2d52a60d8c804fd42b6ac3c90a1c6c6fff0b

 31%|███       | 944/3090 [1:15:44<2:33:35,  4.29s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d209b5d2a23b1291f2d326b63f1940fb5fcffa55

 31%|███       | 945/3090 [1:15:48<2:36:34,  4.38s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/398978ab613d42e199c4eb3ae64348be90644680

 31%|███       | 946/3090 [1:15:53<2:38:57,  4.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/38d30d9cbf6337b025e3251efb517cf13cc72fab

 31%|███       | 947/3090 [1:15:58<2:46:04,  4.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/31e3931c473d786120580cc8ddc09e24fd8af3e7

 31%|███       | 948/3090 [1:16:02<2:43:21,  4.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0d2dde537d01595a67beb4d3219b8185d27ed366

 31%|███       | 949/3090 [1:16:06<2:37:43,  4.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/fc7ade391cd5e44bf38ebca8ea687962e0353ebb

 31%|███       | 950/3090 [1:16:11<2:42:53,  4.57s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4a17d7fc98d3ab10b708957325430113824f71ee

 31%|███       | 951/3090 [1:16:16<2:41:45,  4.54s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6572c37266da74541c12b297f83b2ccd7d8d06c0

 31%|███       | 954/3090 [1:16:31<2:55:38,  4.93s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d1db90ec573a03a99125330677faf318fd40b78a

 31%|███       | 956/3090 [1:16:42<3:02:47,  5.14s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9e69dfccee4b1f5cb0dee1f7f7e8966f79409496

 31%|███       | 957/3090 [1:16:47<3:01:10,  5.10s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c3763140ee333f9fc59110794e0b34595e320a40

 31%|███       | 958/3090 [1:16:54<3:18:06,  5.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/18fcd8bd19b71b72618a3b3deba3ecfab3cc9780

 31%|███       | 959/3090 [1:16:59<3:14:49,  5.49s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8fcf55a799ddb9e5d9d1f849e3219b19e77e1433

 31%|███       | 960/3090 [1:17:04<3:10:49,  5.38s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/47b2dcfd047f18d242002cddc97d87ec6f0f17b9

 31%|███       | 961/3090 [1:17:10<3:15:30,  5.51s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/33b5bc7e7e48fe2e8103c1d967edb8cd4fff526c

 31%|███       | 962/3090 [1:17:14<3:01:35,  5.12s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/34cec9687c2dff673d76f68b538b2c1bd5031ef3

 31%|███       | 963/3090 [1:17:19<2:54:58,  4.94s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/74ddffbfd5bc947b44f03d99e7b89453bdb9fce2

 31%|███       | 964/3090 [1:17:22<2:42:41,  4.59s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a879928e33928eeef6c5d3bef317a9eba9b11ba3

 31%|███       | 965/3090 [1:17:26<2:33:00,  4.32s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4d82202556e22fa600d3bb0ca7d1d99bd0bf544b

 31%|███▏      | 967/3090 [1:17:34<2:30:27,  4.25s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/38f068c1171514b64342a088a80635569ef32c5a

 31%|███▏      | 968/3090 [1:17:39<2:31:59,  4.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d5a1c7d4384b673317ba8309532a0dea17751b16

 31%|███▏      | 971/3090 [1:17:51<2:29:31,  4.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/82e95e37e2a00154e3ff301ab64b2dcd36444732

 31%|███▏      | 972/3090 [1:17:56<2:33:41,  4.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/240c864a4abd03b4dbef3c86b1a27fd9f7e69781

 32%|███▏      | 975/3090 [1:18:11<2:49:06,  4.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/bb93f147568ce51c993a7438733a77709dc1c6fa

 32%|███▏      | 976/3090 [1:18:16<2:54:13,  4.95s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ecad4e0dabaf2937037a0e9c3f6b0d0d647d62fc

 32%|███▏      | 977/3090 [1:18:22<3:06:23,  5.29s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e7abbe7d8dab0b0bc90cf27dcb3114678180e814

 32%|███▏      | 981/3090 [1:18:48<3:39:36,  6.25s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6bdbeade6b5f6fac37649759445eedaa07a33a93

 32%|███▏      | 983/3090 [1:19:02<3:50:51,  6.57s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/75fbd7495f0be0023c8925fa55f140a179d0d495

 32%|███▏      | 986/3090 [1:19:21<3:43:16,  6.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3dd5fea1b1480bfc72898c60b53f31c04c9d5424

 32%|███▏      | 987/3090 [1:19:26<3:34:21,  6.12s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d9e3816d7bc03390e3a0f7a8e7105ebf8866ebcd

 32%|███▏      | 990/3090 [1:19:42<3:17:36,  5.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2902bfaf327556922d30d88a37f9946cd2ce7c33

 32%|███▏      | 992/3090 [1:19:54<3:32:22,  6.07s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2eb50b73700401b8cb812ccc721b477fda7d1515

 32%|███▏      | 994/3090 [1:20:05<3:21:55,  5.78s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9a2862f44f81097e87d933569259201306e2e0f0

 32%|███▏      | 995/3090 [1:20:11<3:14:54,  5.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/25c3841a905553a370f89d657f3376f63207dc3b

 32%|███▏      | 997/3090 [1:20:21<3:12:41,  5.52s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5e6f956a5d33925e6b1b0f177705b1169af89d02

 32%|███▏      | 998/3090 [1:20:26<3:06:43,  5.36s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/47ad0c4f3df61fed24e6dbf4293e1ce33682569d

 32%|███▏      | 999/3090 [1:20:32<3:08:30,  5.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8954c255dfe5dcb3cbbd80f281e2b7913db26447

 32%|███▏      | 1000/3090 [1:20:38<3:10:04,  5.46s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f451c70539ddf430c73bec1f734e01b82839743a

 32%|███▏      | 1001/3090 [1:20:43<3:09:13,  5.43s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/04d4cc36d377d48c95d37940c5a0db265dd7b2c2

 32%|███▏      | 1002/3090 [1:20:48<3:06:52,  5.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d65880957fe94307a8f36f2e523036e412097583

 32%|███▏      | 1003/3090 [1:20:54<3:13:45,  5.57s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d8966dfd89d71ac4a24140541fd6e99f1b5f4a4b

 32%|███▏      | 1004/3090 [1:21:00<3:13:13,  5.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e53ddac28064fecde611d38afea4f23f1f423073

 33%|███▎      | 1005/3090 [1:21:05<3:12:18,  5.53s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9fd889ceeaaf704c533b1a9fd9eb54ab8ea1c95d

 33%|███▎      | 1006/3090 [1:21:11<3:18:35,  5.72s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3b4e6f239bb668e8de80ab9203ce8c357445b916

 33%|███▎      | 1007/3090 [1:21:17<3:14:56,  5.61s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d23671bc4e643569f31f6e24ad3b20a72d3f4b4f

 33%|███▎      | 1008/3090 [1:21:22<3:09:16,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/434b30d074c5026ae2c7e05a0faf4179baa2c656

 33%|███▎      | 1009/3090 [1:21:27<3:08:15,  5.43s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b1ce6c994bd5f17ba7a04587daec2ccfc40b2d44

 33%|███▎      | 1010/3090 [1:21:32<2:58:53,  5.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d6d1fafdecff97299f725adcd3e5c6c409c2cd35

 33%|███▎      | 1011/3090 [1:21:38<3:06:00,  5.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1a07e7d93eb45ba25873f80dd373163962d87bcd

 33%|███▎      | 1012/3090 [1:21:43<3:08:54,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/63da4397d04608a82c45c774e38a84e7f056b1e6

 33%|███▎      | 1014/3090 [1:21:57<3:28:49,  6.04s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5a09913af1130fc48c2f74db4be69de9e71af487

 33%|███▎      | 1017/3090 [1:22:15<3:26:13,  5.97s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/16ed025f1b0949fa5ff7a393b427485532b6278d

 33%|███▎      | 1018/3090 [1:22:19<3:14:09,  5.62s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2ec59e20d1a089de6242365e46e9d2627855541c

 33%|███▎      | 1019/3090 [1:22:28<3:45:40,  6.54s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/46198a1b4402c40a6242f9831ca7609feafeb18a

 33%|███▎      | 1021/3090 [1:22:42<3:53:27,  6.77s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/352dea73e3f72ba1597892e9c230ed869c3f701b

 33%|███▎      | 1022/3090 [1:22:48<3:44:54,  6.53s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/be1f2d094251c1a0c6bbfb432b0c2dc0ed2ed31e

 33%|███▎      | 1023/3090 [1:22:54<3:34:21,  6.22s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/516301c6debde3287d21fa55384818d37e1508ec

 33%|███▎      | 1024/3090 [1:23:00<3:36:03,  6.27s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f756bcefdb0b1050a6f892b34f01048bbc64bfb8

 33%|███▎      | 1026/3090 [1:23:12<3:28:33,  6.06s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ca69571b8dd3a4f70fd49e872ded6abe6e40acec

 33%|███▎      | 1027/3090 [1:23:18<3:28:15,  6.06s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8c071803ec772d51cae89104b6673928560a727b

 33%|███▎      | 1031/3090 [1:23:43<3:35:13,  6.27s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3b20166445617c7414f62536551e4758a84a4219

 33%|███▎      | 1033/3090 [1:23:55<3:31:12,  6.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8656e1893d1e3c79a573579931133145bbc3239f

 33%|███▎      | 1034/3090 [1:24:00<3:20:24,  5.85s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ef2d4bd79fd93fbfa6f6b227b3249c2dec0d6904

 33%|███▎      | 1035/3090 [1:24:05<3:18:05,  5.78s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/bbd09e0ad6bec99a0e7e68e9772f2ad747d245f1

 34%|███▎      | 1036/3090 [1:24:11<3:18:32,  5.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/775dc835c7a3759202309c589f58472dd12f5cc7

 34%|███▎      | 1037/3090 [1:24:17<3:14:50,  5.69s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/16799669f0c75683ed4c9fa8ecf1c8b5c369cad0

 34%|███▎      | 1038/3090 [1:24:22<3:12:51,  5.64s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b86b9f0e4258be30cf0eca0102192b9b675ef1f6

 34%|███▎      | 1039/3090 [1:24:30<3:30:31,  6.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ee14e77e31a9c309fd21ca1e9b1322281102efc5

 34%|███▎      | 1040/3090 [1:24:35<3:24:23,  5.98s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/39d8463e3f3359bb9443989984343bbd26bf3695

 34%|███▎      | 1041/3090 [1:24:41<3:25:32,  6.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d0e158e0a5f98b45c5d650df63d7005dcf6d0257

 34%|███▎      | 1042/3090 [1:24:48<3:30:56,  6.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/56bcf8e6a5adb38a32a02f86e9324234cc5ded32

 34%|███▍      | 1043/3090 [1:24:53<3:22:36,  5.94s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d788dcd2f850f03488f6d6578f37495c5bd7d505

 34%|███▍      | 1045/3090 [1:25:04<3:12:51,  5.66s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5ea3ce7ee879db537599321a8efea2620b78c186

 34%|███▍      | 1047/3090 [1:25:15<3:07:42,  5.51s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/26493c912cacdbe299ac61a65e2f9a280edaa09c

 34%|███▍      | 1049/3090 [1:25:27<3:12:56,  5.67s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dd74ffddde36781f8a780a33d6fe116ae0418fb9

 34%|███▍      | 1050/3090 [1:25:32<3:01:28,  5.34s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/84f1590674634e2727c8f65d2b0079478d502096

 34%|███▍      | 1051/3090 [1:25:40<3:29:57,  6.18s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 34%|███▍      | 1052/3090 [1:25:45<3:20:07,  5.89s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/849c604a97aba470b5d979360e82884ac90cf91c

 34%|███▍      | 1053/3090 [1:25:51<3:27:05,  6.10s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1210bc26acb2742f28cd6645b1d682144889261b

 34%|███▍      | 1055/3090 [1:26:03<3:21:52,  5.95s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/071b26ac2d912620b6eaad247604885fc4af5b56

 34%|███▍      | 1056/3090 [1:26:11<3:36:24,  6.38s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/87eff1267a7550b2b222b6df4f473d35381c9f50

 34%|███▍      | 1058/3090 [1:26:24<3:38:02,  6.44s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/459f62a9455282e280035791a0f82071381efc30

 34%|███▍      | 1059/3090 [1:26:32<3:50:30,  6.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1e6e47dfb7ad1545408c70bb4c2636282ed60bf6

 34%|███▍      | 1060/3090 [1:26:37<3:37:35,  6.43s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/cc32f84cf1521d03acd0c5d87fe065d9c9af2ef1

 34%|███▍      | 1063/3090 [1:26:56<3:32:02,  6.28s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8703ef34032b32ca1dd01f442252a88f4efcc4ca

 34%|███▍      | 1064/3090 [1:27:02<3:30:21,  6.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f40865473c2afb9053c92eb3469868721a04ed80

 34%|███▍      | 1065/3090 [1:27:08<3:26:56,  6.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/85c30e434a2d81f61bb16981cccdda94d3766ee9

 34%|███▍      | 1066/3090 [1:27:14<3:26:24,  6.12s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/fed84baa3ee04fc05bdfdf259c11fa9e902fb5cc

 35%|███▍      | 1067/3090 [1:27:19<3:19:52,  5.93s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/60684bada63fc2aa6e98a649db30e2d7b4426c89

 35%|███▍      | 1068/3090 [1:27:25<3:16:44,  5.84s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5ae9e0bca774a93c84299042aba569f9aba21746

 35%|███▍      | 1069/3090 [1:27:31<3:17:37,  5.87s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9e117a677f43cbb9a58d2ed424d094e69761460d

 35%|███▍      | 1070/3090 [1:27:37<3:14:10,  5.77s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b7eb67bdbd4faa9d383bd3c5190998ccb35f23d8

 35%|███▍      | 1071/3090 [1:27:42<3:11:41,  5.70s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4fd42d79fee1950461081a165854e4a8e97c0de4

 35%|███▍      | 1073/3090 [1:27:54<3:14:05,  5.77s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/182bf1e52ea27b142a0dec4dd4a236c709a4dc4b

 35%|███▍      | 1076/3090 [1:28:15<3:57:32,  7.08s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8051d3e2bf9d52a8d45b5d31629934fb4a91a0ad

 35%|███▍      | 1077/3090 [1:28:23<4:02:24,  7.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1c606f4faeee932ca48e4b45fe19c12c1a9a5f99

 35%|███▍      | 1078/3090 [1:28:28<3:44:11,  6.69s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1140bb93bc57e052462074fb3bcde6b9ce4a0d37

 35%|███▍      | 1079/3090 [1:28:34<3:34:52,  6.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c7d14c5e0f930e4e5ba7adedb9f92a5b23db3d5e

 35%|███▍      | 1081/3090 [1:28:45<3:23:42,  6.08s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1a856729fc870ebb65bac354e662aaadcf5588b3

 35%|███▌      | 1083/3090 [1:28:56<3:09:36,  5.67s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/20fbd8defc89a248a0388bdef7e95baa0027267f

 35%|███▌      | 1085/3090 [1:29:07<3:08:21,  5.64s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a13408e9226060e594aeb2ce9bd8d0f189396993

 35%|███▌      | 1086/3090 [1:29:13<3:06:14,  5.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3e3c9f074a0cbf3d62784576b1364adea9ecb78e

 35%|███▌      | 1087/3090 [1:29:18<3:06:12,  5.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/852151396b6174eac3a524b2611c41221911ae40

 35%|███▌      | 1091/3090 [1:29:41<3:08:10,  5.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dd9f1cea8f375a09c17c2681ead9fd47ead4fb54

 36%|███▌      | 1098/3090 [1:30:30<4:37:15,  8.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f2f531958bb58b521d1cb07a1cf0d4beabca2887

 36%|███▌      | 1099/3090 [1:30:36<4:13:06,  7.63s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/552f65770fb7ef9ce9e3d65b913fdc56db326f31

 36%|███▌      | 1101/3090 [1:30:47<3:30:23,  6.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8f5527581451c31fbb681eccfa8a253bc2328011

 36%|███▌      | 1102/3090 [1:30:52<3:20:00,  6.04s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/21b93c75fec001d462a0d67c55ca2c0511f3d04f

 36%|███▌      | 1103/3090 [1:30:58<3:19:23,  6.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/975fda0477c473c205f3f2338fe86c270c5b1489

 36%|███▌      | 1104/3090 [1:31:03<3:09:19,  5.72s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/910e064bfb3148f10bbcbebcc66e4a6a9549aa44

 36%|███▌      | 1105/3090 [1:31:10<3:21:01,  6.08s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d670f9998be7e9ac0682a18d75a7474ebb1d4084

 36%|███▌      | 1107/3090 [1:31:21<3:11:01,  5.78s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/630add957fd5ec8bfee234973bb62cf08b3b9940

 36%|███▌      | 1109/3090 [1:31:33<3:13:14,  5.85s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/23d42a87046eb6d3f0fcd81e7d63923aff50e702

 36%|███▌      | 1110/3090 [1:31:39<3:15:01,  5.91s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d5a10ac61f58f8eefa67c11cf470570c4af1980a

 36%|███▌      | 1113/3090 [1:32:02<3:47:31,  6.91s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4db6834b469852f6f413307591cd8d1f25e27749

 36%|███▌      | 1117/3090 [1:32:40<4:28:49,  8.17s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4f2fef52a42da586aeb98e216f2264564cc844e4

 36%|███▌      | 1118/3090 [1:32:46<4:08:03,  7.55s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/76c6f5815db05a30a06023a4a29701939d467586

 36%|███▌      | 1120/3090 [1:33:00<3:56:57,  7.22s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e7bc78a94bc3b7ad7eabda16d42c636b50c05306

 36%|███▋      | 1121/3090 [1:33:06<3:43:14,  6.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/379623ad0f87d5391348bc514a06f8b2614384d8

 36%|███▋      | 1122/3090 [1:33:12<3:37:44,  6.64s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/38a0792ac64052625a003005b6de0de549f14c2f

 36%|███▋      | 1123/3090 [1:33:17<3:23:38,  6.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8e4a19ec45192ea3d1a419a9fcc2dd97e21de773

 36%|███▋      | 1126/3090 [1:33:37<3:23:18,  6.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3f76b3dfb59cd26999fa27c178592349bed0208d

 36%|███▋      | 1127/3090 [1:33:44<3:25:30,  6.28s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/011a29ebf74655136bdb9b1c94aa492663c58aaf

 37%|███▋      | 1128/3090 [1:33:49<3:15:01,  5.96s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5667af166053470191fa0e66b2019b3b3001b8bd

 37%|███▋      | 1130/3090 [1:34:03<3:30:04,  6.43s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/df71c1a07ceb7878f745e42c713b698f8034e79d

 37%|███▋      | 1132/3090 [1:34:19<3:44:57,  6.89s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e5092f0fdd888015ba507a36d555437b4eacd2f9

 37%|███▋      | 1134/3090 [1:34:35<4:04:21,  7.50s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f20e52df792b4d5ad1dc32c66ba068f87c6aad56

 37%|███▋      | 1135/3090 [1:34:41<3:47:01,  6.97s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e1615c8e57303628a4a7293fd0ac9e0ca75af768

 37%|███▋      | 1136/3090 [1:34:49<4:01:33,  7.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/99cbd7a58d76e3ff6deecbe40695dbbf7c812dc2

 37%|███▋      | 1137/3090 [1:34:58<4:17:20,  7.91s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/984dccb2e9d3e8eea1789c0b2a86bdd443e76d25

 37%|███▋      | 1139/3090 [1:35:15<4:24:18,  8.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2c8902075c5e707bf5833e00569bc44c31d85828

 37%|███▋      | 1140/3090 [1:35:22<4:07:42,  7.62s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ce807881777d99bd3c4517121c7b2ad3e45687fd

 37%|███▋      | 1141/3090 [1:35:28<3:51:36,  7.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/bd22f4ed4736cd572aa4b878d69e69086b9aa0bb

 37%|███▋      | 1142/3090 [1:35:34<3:38:34,  6.73s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b7deb7e08a3de694145841f941ffa2c6ec4e8c0e

 37%|███▋      | 1144/3090 [1:35:48<3:44:37,  6.93s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f31682a96f55c9e8ec2d9322101336c8486e36b4

 37%|███▋      | 1145/3090 [1:35:53<3:31:55,  6.54s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1a37849029ef44c845a00d07410612a2273c4f7e

 37%|███▋      | 1147/3090 [1:36:06<3:26:11,  6.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6b247c82bf2e44f897a8b7348fe5a9f946d990bc

 37%|███▋      | 1148/3090 [1:36:12<3:20:33,  6.20s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/469724549b874a8de119d03c3d9ba21b4b12fc19

 37%|███▋      | 1149/3090 [1:36:19<3:24:30,  6.32s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f44a174f5f18b58b33b4e2c94f5b46911726734a

 37%|███▋      | 1150/3090 [1:36:26<3:35:34,  6.67s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/fe37ac9daf621d9bde75d4346807826250c85bfa

 37%|███▋      | 1151/3090 [1:36:34<3:44:17,  6.94s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a882b5006ba90a4c965eddb8023acffe76f08f1f

 37%|███▋      | 1152/3090 [1:36:44<4:17:08,  7.96s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/72eaebbd729b774f45b48c118693ec98e6c9401f

 37%|███▋      | 1154/3090 [1:37:01<4:23:47,  8.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/53e7903ba499f59da9b05376d696721f103f8533

 37%|███▋      | 1156/3090 [1:37:17<4:15:26,  7.92s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/cd7bddf6915538a7718fda4c4ba084f72d941d38

 37%|███▋      | 1157/3090 [1:37:25<4:12:34,  7.84s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5311e754d4fc412a337f6c994e0cd85363b9b87c

 37%|███▋      | 1158/3090 [1:37:32<4:05:37,  7.63s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/713a990930b041210deddcedb6301d2cd775957a

 38%|███▊      | 1159/3090 [1:37:38<3:45:56,  7.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f76a557305ddec2c0406f6556b67097019db4f4c

 38%|███▊      | 1160/3090 [1:37:44<3:35:06,  6.69s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4ff1eb2c51e205d95577bea8ecf75f496ea54031

 38%|███▊      | 1161/3090 [1:37:51<3:38:57,  6.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b172781774147983b12fea05f02a457068b349c9

 38%|███▊      | 1162/3090 [1:37:58<3:48:12,  7.10s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/aac602ad7e953f77c5e3ca1de167621435ac7521

 38%|███▊      | 1164/3090 [1:38:12<3:41:25,  6.90s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/69544dccc1d570c26d8503da29e9d051f8609211

 38%|███▊      | 1165/3090 [1:38:19<3:46:20,  7.06s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9c0f60292d6add2d65b4de1aeb95bc39fd89c9c9

 38%|███▊      | 1166/3090 [1:38:25<3:35:06,  6.71s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9a6e0f37483e6eae1e606bf885790f78b0a2e496

 38%|███▊      | 1167/3090 [1:38:31<3:27:06,  6.46s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/725b6c445a2b506e2655d3eb216deeb6e0d45478

 38%|███▊      | 1169/3090 [1:38:48<3:56:06,  7.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ccac80d6f4cdf94216ed308473f7eeefdc8760a1

 38%|███▊      | 1170/3090 [1:38:56<4:04:50,  7.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6eb4fe5a2f3dafdacf24cf3b390202bdd3918092

 38%|███▊      | 1171/3090 [1:39:06<4:22:39,  8.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/435365a84233571594c4a7a11b1dd248a9316bb0

 38%|███▊      | 1173/3090 [1:39:26<4:57:26,  9.31s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ae134c476513dd6171710191636111588cc98b8f

 38%|███▊      | 1174/3090 [1:39:35<4:47:30,  9.00s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d99b83ae5a67fef6e06c9b62f0a9e62833cba339

 38%|███▊      | 1178/3090 [1:40:07<4:13:32,  7.96s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/36c5a1faa0830ca5afc8af0f227b256ecaf8195c

 38%|███▊      | 1179/3090 [1:40:14<4:09:12,  7.82s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d17cdc6bf5e5dc04667fd53f27cee014f37767aa

 38%|███▊      | 1181/3090 [1:40:35<4:34:37,  8.63s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/666edd7f750f76c6c87fc513e80a84cd92e0e744

 38%|███▊      | 1182/3090 [1:40:39<3:51:41,  7.29s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5218dce6699fa1d8419bf441553873aeaedec39f

 38%|███▊      | 1185/3090 [1:41:05<4:05:14,  7.72s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6df9a306824c1a62f7259f425f55a35e7920a8dc

 38%|███▊      | 1187/3090 [1:41:20<3:58:18,  7.51s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/681bd485e2a252e2bd295050bf76084f6e2a26ee

 39%|███▊      | 1193/3090 [1:42:14<4:22:24,  8.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6edf454b8523b303d2e2fab4a73682962fc44e23

 39%|███▊      | 1195/3090 [1:42:25<3:34:36,  6.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5d8d564b9370190ea1cbe5b2ea7c095ce47c725b

 39%|███▉      | 1199/3090 [1:42:56<3:37:22,  6.90s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0905a1c90dbe49508bb5d3e0103ec52d13c0487b

 39%|███▉      | 1201/3090 [1:43:10<3:39:45,  6.98s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/524b0693ba802edce5d6e53ebfe47fae99417cb4

 39%|███▉      | 1202/3090 [1:43:16<3:25:57,  6.55s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e76a4da99dae89bff255652f58e31390a9e508ee

 39%|███▉      | 1209/3090 [1:44:05<3:19:51,  6.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c3c8491443c705fc6e94f75e7c4b5815f65cab71

 39%|███▉      | 1210/3090 [1:44:10<3:07:22,  5.98s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/406ce2f0e577e3d877d61e3287c7e5e699d8c437

 39%|███▉      | 1211/3090 [1:44:15<2:57:31,  5.67s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7b32711c2a578e1c7917593484b245f443cb9ca4

 39%|███▉      | 1212/3090 [1:44:21<2:54:34,  5.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/285ad4dfc361a96efe74855b3128de016ba3d30a

 39%|███▉      | 1214/3090 [1:44:30<2:37:11,  5.03s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d1dee3145416b31ccd160f73c3f6f3c83e3ca9dd

 39%|███▉      | 1216/3090 [1:44:40<2:36:29,  5.01s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e94eb0e4e7fc4b0f5a3f9de966470998b6d30b20

 40%|███▉      | 1221/3090 [1:45:15<3:31:54,  6.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ecd4c62c5cd7a28b04cd38760a3be38c50c71cec

 40%|███▉      | 1224/3090 [1:45:36<3:24:16,  6.57s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c21441df2e86f2f821d4c5474c9b23bbe6f54660

 40%|███▉      | 1227/3090 [1:45:57<3:26:24,  6.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e73104ef6b403d41ef338704ff2b29b73560601a

 40%|███▉      | 1231/3090 [1:46:22<3:03:20,  5.92s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5db21b302d434b08cb9a679c98153d6f96dd70b5

 40%|███▉      | 1232/3090 [1:46:27<2:55:50,  5.68s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5db21b302d434b08cb9a679c98153d6f96dd70b5

 40%|███▉      | 1233/3090 [1:46:32<2:48:59,  5.46s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/34aedb7ab591f43e7ea1d03e736e8dc1b8cee908

 42%|████▏     | 1297/3090 [1:52:27<2:48:47,  5.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/04d276a3fb1bf9ed568f0f7edf8b0d60207d5c94

 44%|████▍     | 1353/3090 [1:57:32<2:28:36,  5.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f798d5aec1f879148aa1eed3ec1f23a3ffa7bdda

 44%|████▍     | 1355/3090 [1:57:41<2:19:27,  4.82s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/84bf95b3c655276a9677287287b5b8b23c648d68

 44%|████▍     | 1356/3090 [1:57:47<2:29:02,  5.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9b07f7c163ac3f7200f15dd400dbafb0b8223daf

 44%|████▍     | 1357/3090 [1:57:52<2:30:25,  5.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c0ce1a0efd996a1c14027ced591ffaeefd5335d5

 44%|████▍     | 1359/3090 [1:58:00<2:12:29,  4.59s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8e42e29fda871771a1e22ebc95d96aac2bf097f3

 44%|████▍     | 1360/3090 [1:58:07<2:26:12,  5.07s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/609ec04b81ccc2b3ee4d582443ae027ae65e3a01

 44%|████▍     | 1361/3090 [1:58:11<2:21:45,  4.92s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/74dc5db45d077ef5db9091f58dea0ec19fff0b74

 44%|████▍     | 1362/3090 [1:58:15<2:15:26,  4.70s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c278f281d10eba597be065fc68c3a463d9097c44

 44%|████▍     | 1365/3090 [1:58:28<2:05:30,  4.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/98718b72c913ea301842c7f19a8fbe06105ae43d

 44%|████▍     | 1366/3090 [1:58:32<2:03:59,  4.32s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/431bf33b121887b2cab73e43775717f56047c106

 44%|████▍     | 1367/3090 [1:58:37<2:07:16,  4.43s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ce51fd70820a16d46696c1c765ede409b8e9d4c5

 44%|████▍     | 1368/3090 [1:58:41<2:08:45,  4.49s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 44%|████▍     | 1369/3090 [1:58:47<2:15:54,  4.74s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ee8729b392a3dc6511fabc641f6eb766d1fa0bf0

 44%|████▍     | 1370/3090 [1:58:53<2:25:16,  5.07s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/bd7310c0a4f2fd2f2e77180bc01c4c567a595466

 45%|████▍     | 1379/3090 [1:59:36<2:04:35,  4.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b5d614f501ce1e1f641f6af6c31857c30862d8ec

 46%|████▌     | 1412/3090 [2:02:53<2:32:20,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/133d0014d65bfb2e5a1e360d6f70fe96e0379d74

 46%|████▌     | 1428/3090 [2:04:12<2:10:57,  4.73s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dfdc511bd65e1b5038690a685e10555764affd88

 46%|████▌     | 1429/3090 [2:04:16<2:07:12,  4.59s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/64fb78efb8ba032d75ed68f9d0401af41c6567a7

 46%|████▋     | 1430/3090 [2:04:20<2:05:09,  4.52s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2e08267b4465a072058874b5ddce493280fcf39e

 46%|████▋     | 1431/3090 [2:04:25<2:01:51,  4.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c366a812182a8cdb9e3943fa087d4389d7306796

 47%|████▋     | 1437/3090 [2:04:50<2:01:08,  4.40s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b08eeed5273a3e4825b1575c15a4e37118a0f785

 47%|████▋     | 1441/3090 [2:05:08<2:00:48,  4.40s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d2d27f243812fc349d3565ec03b63c9d37b5ddb2

 47%|████▋     | 1443/3090 [2:05:18<2:10:44,  4.76s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4706aed09aa20a83aaa8ca67ff06c9fd110eca6f

 47%|████▋     | 1447/3090 [2:05:38<2:11:16,  4.79s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a139bb372b9978e6937d13d2baa0e2f40f665c24

 47%|████▋     | 1449/3090 [2:05:47<2:13:09,  4.87s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4e7277d8727001a59700839c83aba526f1b01821

 47%|████▋     | 1464/3090 [2:07:07<2:22:57,  5.28s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/874403c11bf18be69471b1bd71e6c4200fd3ec32

 48%|████▊     | 1470/3090 [2:07:37<2:18:00,  5.11s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/da6e9417d466d4bfc083d9d0594c38577d273ead

 48%|████▊     | 1480/3090 [2:08:29<2:07:11,  4.74s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/47cae859d7d6436cff7618bd2a62450462bb7272

 48%|████▊     | 1484/3090 [2:08:49<2:14:23,  5.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8e42e29fda871771a1e22ebc95d96aac2bf097f3

 48%|████▊     | 1487/3090 [2:09:00<1:50:11,  4.12s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a4d21a0aa47984f1754ccb0c5475fb632c7db063

 48%|████▊     | 1488/3090 [2:09:05<1:52:51,  4.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e87c907b4bbaa1462d917407c90f58834f5505d6

 48%|████▊     | 1489/3090 [2:09:10<1:58:36,  4.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/26a7acf3e0b62b94c2befba05ecb6a1e90958f45

 49%|████▊     | 1503/3090 [2:10:44<3:00:55,  6.84s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d4d0d9dd15861baba33cc2f6021435f81a4de25e

 49%|████▉     | 1511/3090 [2:11:34<2:22:34,  5.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6e62f6935c65a33557737f5e8530c1a2e52cc574

 49%|████▉     | 1512/3090 [2:11:37<2:08:14,  4.88s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2adf5782ddbee197745b2015af86daef8d852d12

 49%|████▉     | 1515/3090 [2:12:00<2:48:20,  6.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f2803f6ac08e517e5336f19451b3ae6591d71857

 50%|█████     | 1545/3090 [2:15:37<2:21:53,  5.51s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8e42e29fda871771a1e22ebc95d96aac2bf097f3

 50%|█████     | 1552/3090 [2:16:26<2:48:40,  6.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6eaa45a2694ae339b61bea6701ab42fb58ad6629

 50%|█████     | 1553/3090 [2:16:32<2:42:02,  6.33s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4541f07509ef12318035099d54eeb532457fb982

 50%|█████     | 1554/3090 [2:16:36<2:27:59,  5.78s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e3e6a6727b2abe42c97881d4b0017d05bf1e4630

 50%|█████     | 1556/3090 [2:16:49<2:34:49,  6.06s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dedf58835159ed91b98170bb8f27971228ba1bb5

 50%|█████     | 1560/3090 [2:17:26<3:34:30,  8.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/47d632856aa736e194557351f27580b77a294abb

 51%|█████     | 1561/3090 [2:17:30<3:02:00,  7.14s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/740aeefdbcea694be3880b3df7f50091cf0a48f4

 51%|█████     | 1564/3090 [2:17:50<2:44:25,  6.47s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7577ba5a4ee2bb5a50d656e055019caf44ab69f9

 51%|█████     | 1565/3090 [2:17:54<2:29:25,  5.88s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5f93630a89c7bb963465c1ae90fb4867380787b7

 51%|█████     | 1567/3090 [2:18:08<2:36:51,  6.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/484594854922c8a0c9c7f444f09dc024c8c7fcb3

 51%|█████     | 1569/3090 [2:18:19<2:28:52,  5.87s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3444041d2a7cd05a7011c3eb966878fd81407806

 51%|█████     | 1571/3090 [2:18:28<2:09:51,  5.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4ecb94c54a01dd894d2153596fcb5394b19ae39d

 51%|█████     | 1577/3090 [2:19:11<2:38:25,  6.28s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/44525a76fa265edc2bf5cfb3ee5d4f1c9e25685c

 51%|█████     | 1578/3090 [2:19:16<2:23:54,  5.71s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7735957953640b02c31dae5f90b67621c992ee69

 51%|█████     | 1581/3090 [2:19:35<2:31:28,  6.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d1e1a5056692f9dd3f024e500bdb81b0048c0849

 51%|█████▏    | 1587/3090 [2:20:17<2:38:35,  6.33s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0b2dfc882d378b21e450f2bb35e1d53df8ea0932

 51%|█████▏    | 1589/3090 [2:20:30<2:38:06,  6.32s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/21fea30c052150a1ab7fcdec38a83103633e76e3

 52%|█████▏    | 1592/3090 [2:20:50<2:35:05,  6.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/af72dc580f18c5e389f80fd068bae1771e628c75

 52%|█████▏    | 1594/3090 [2:21:04<2:43:51,  6.57s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9bf77d6f28ecb54957cc410efdbf484b0b649c27

 52%|█████▏    | 1600/3090 [2:21:48<2:34:27,  6.22s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3692091aa607622133c505c013c03ad3dc21f6c0

 52%|█████▏    | 1610/3090 [2:22:58<2:43:12,  6.62s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8e42e29fda871771a1e22ebc95d96aac2bf097f3

 52%|█████▏    | 1611/3090 [2:23:02<2:23:17,  5.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7832c4122cb33c33e1602de5421ebd31b632af21

 53%|█████▎    | 1629/3090 [2:24:37<1:59:11,  4.89s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9f9b8dbddaeb16dbe32626618e64c7df0688cb93

 53%|█████▎    | 1637/3090 [2:25:18<2:00:21,  4.97s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/eb38fc03bdad19d216aec788675643885e840397

 53%|█████▎    | 1638/3090 [2:25:21<1:52:53,  4.66s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0e9a3942b851ffdcc674ef49c309db75eb887b8d

 53%|█████▎    | 1639/3090 [2:25:26<1:50:10,  4.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f466a4174ad9d529eb6e5474a7985d0d9c388543

 53%|█████▎    | 1640/3090 [2:25:30<1:46:42,  4.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f2f00fd43ee9d24109f78dcddeffa15ab52f6b7e

 53%|█████▎    | 1641/3090 [2:25:34<1:47:20,  4.44s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7e5d39be6db3aede4eaf9910159a0246ae9426a2

 53%|█████▎    | 1650/3090 [2:26:38<2:30:58,  6.29s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a08ff09a9c62bf383497d79fbe268f548364715b

 53%|█████▎    | 1651/3090 [2:26:52<3:26:29,  8.61s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6e8bc84a61852bad0aaf0add4e7a181257afb475

 54%|█████▎    | 1656/3090 [2:27:28<2:50:18,  7.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/541f654a304fc331b9fc6b0ef2f2ea8a229b1b81

 54%|█████▍    | 1667/3090 [2:28:47<2:33:44,  6.48s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6a82e2a9be08b173e3b2eaba347ef2d57fdc74e6

 54%|█████▍    | 1670/3090 [2:29:07<2:30:46,  6.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/260059de234cd896aff97cbb54172d89c4c71b18

 54%|█████▍    | 1675/3090 [2:29:40<2:26:45,  6.22s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/98b5ad6b73117b97b2c0153d93d3c76775f51012

 54%|█████▍    | 1680/3090 [2:30:21<2:50:45,  7.27s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f461b0a9cf5685a9533c7e681d194015d4d298fb

 54%|█████▍    | 1681/3090 [2:30:25<2:29:27,  6.36s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2d4fbbb9ddcb191bceb361a422e75ca64c1b0832

 54%|█████▍    | 1684/3090 [2:30:45<2:28:27,  6.34s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ba691fa5a7dbd5e2832dbb54bc8a43e49079106a

 55%|█████▍    | 1687/3090 [2:31:05<2:30:39,  6.44s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e2f233f340f34594289dfa104fd91e3dc15ada5a

 55%|█████▍    | 1689/3090 [2:31:18<2:23:16,  6.14s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b8bf20679b88dff9d5c9ae5ce88855c0fb66f92a

 55%|█████▍    | 1690/3090 [2:31:23<2:17:34,  5.90s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 55%|█████▍    | 1694/3090 [2:31:51<2:28:36,  6.39s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2eb361fdcf447290eb3e8bfd007e7b56c105abed

 55%|█████▍    | 1696/3090 [2:32:04<2:29:08,  6.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/89cb0d289eef2d2644adc753b2020c2c6c43e88e

 56%|█████▌    | 1715/3090 [2:33:59<2:12:30,  5.78s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 56%|█████▌    | 1716/3090 [2:34:15<3:18:18,  8.66s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0efb3cd68969f6bd601a17d57dab6a3ee8576db9

 56%|█████▌    | 1717/3090 [2:34:19<2:49:49,  7.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3e22277e94e0e6546648cc45e1bc3dda9887bda8

 56%|█████▌    | 1718/3090 [2:34:23<2:26:35,  6.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9b61c6f426c05d7b92982334e4988dfe43825b45

 56%|█████▌    | 1720/3090 [2:34:35<2:18:55,  6.08s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b08b29aba4e76a28ef91fdd19194fccd2786d07b

 56%|█████▌    | 1721/3090 [2:34:41<2:11:32,  5.76s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9ab819253484b73dce05fe2def0c65df6b3e4446

 56%|█████▌    | 1725/3090 [2:35:10<2:33:28,  6.75s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d2ed74e0ef11972cddc9ed1a7afeae32d4bbfc75

 56%|█████▌    | 1731/3090 [2:35:57<2:41:13,  7.12s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7dc93a62e0a3f9ab6f208e736ba607e737b653b9

 56%|█████▌    | 1737/3090 [2:36:37<2:15:02,  5.99s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/466b2b704ae7b3ae9a8edce5497fd3528bfaf9ea

 56%|█████▋    | 1739/3090 [2:36:53<2:39:25,  7.08s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/01fca059157519f0b760e630097d61f28c8a1dca

 56%|█████▋    | 1741/3090 [2:37:05<2:23:16,  6.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e8824181832aeeff780c4ced99a8f04cb2961746

 56%|█████▋    | 1743/3090 [2:37:19<2:27:12,  6.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ab9a0d0c8e762a760569192b237b3073b9c8aa34

 56%|█████▋    | 1744/3090 [2:37:24<2:14:24,  5.99s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e59f01da58d80320af773fe611ac0b241b475e13

 57%|█████▋    | 1746/3090 [2:37:36<2:12:45,  5.93s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dd570c1c253093484fb6a408dc942e548bd551a5

 57%|█████▋    | 1749/3090 [2:37:56<2:18:05,  6.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3e087409bb08e6f55d8a20705f8fa7957046de11

 57%|█████▋    | 1752/3090 [2:38:17<2:21:11,  6.33s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/492ff6b679373559c969546e14c3df26b773d616

 57%|█████▋    | 1754/3090 [2:38:28<2:11:19,  5.90s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/40873cad1e73c4ef4ac2a6a0b494df57f30b4883

 57%|█████▋    | 1755/3090 [2:38:32<1:57:09,  5.27s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d53f4552e8f3d2ec9ec4144dafe88a85c2bb2622

 57%|█████▋    | 1757/3090 [2:38:44<1:59:38,  5.39s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/de66c7cd1f3650364f5d08e6db70599f64a2fd04

 57%|█████▋    | 1758/3090 [2:38:48<1:51:15,  5.01s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b70102bd0d750f8a080704d93135d196d63ca3d1

 57%|█████▋    | 1763/3090 [2:39:22<2:10:40,  5.91s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5c25893c0e3ed92a4114daa6d94213d6a830022e

 57%|█████▋    | 1767/3090 [2:39:48<2:15:47,  6.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/8846c16c6dab7b103b8fd20dcdf76a04a4658985

 57%|█████▋    | 1768/3090 [2:39:53<2:06:06,  5.72s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 57%|█████▋    | 1769/3090 [2:39:58<2:01:18,  5.51s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 57%|█████▋    | 1772/3090 [2:40:19<2:17:07,  6.24s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9358cbcc97872eb66899b96eb82256b3b274f5d8

 57%|█████▋    | 1773/3090 [2:40:23<2:04:54,  5.69s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/05c7ae4b88b06f5103ae4a00aebb38ce9852c83c

 58%|█████▊    | 1779/3090 [2:41:05<2:24:08,  6.60s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d381391d5e5c873dbebaff193bf4898939e69c40

 58%|█████▊    | 1790/3090 [2:42:27<2:24:14,  6.66s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ab5a3ee384c0dfebe9c6d6ec946f402afb3f3474

 58%|█████▊    | 1793/3090 [2:42:48<2:24:57,  6.71s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b9b21bb99ff0a144e53e4c0b9cdd9f793d9b6093

 58%|█████▊    | 1795/3090 [2:43:00<2:11:01,  6.07s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5365d6fa5e0a00521302122e5ad8467cac97ca4a

 58%|█████▊    | 1803/3090 [2:44:07<2:35:53,  7.27s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d31655b3f82038c513eed0e4a84c8f1c89d5bfdb

 58%|█████▊    | 1805/3090 [2:44:25<2:56:09,  8.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7857fa69055467ad8a7ce51a9f2aba0e65af2ecc

 59%|█████▉    | 1824/3090 [2:46:43<2:00:10,  5.70s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9a036904ff3bc72e6fa93a1efbfef26c542d8155

 59%|█████▉    | 1825/3090 [2:46:49<2:02:36,  5.82s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3034a802102079c83361af020e070bf53c10a899

 59%|█████▉    | 1826/3090 [2:46:53<1:54:45,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3034a802102079c83361af020e070bf53c10a899

 59%|█████▉    | 1827/3090 [2:46:59<1:56:29,  5.53s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 59%|█████▉    | 1828/3090 [2:47:03<1:48:56,  5.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a023a8f93781daeb8b7ac5eb96e91f461583bda9

 59%|█████▉    | 1832/3090 [2:47:34<2:23:38,  6.85s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/12a4287ea57aa7fdd21cd7527af6dd92ed1855b0

 59%|█████▉    | 1833/3090 [2:47:38<2:05:45,  6.00s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0ed93cc94729a6b9b81f341846d69e8989212e3c

 59%|█████▉    | 1834/3090 [2:47:46<2:12:47,  6.34s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0cb6e9c71e2a29809fe69c14ec64ebdc278b9cac

 59%|█████▉    | 1835/3090 [2:47:51<2:04:20,  5.94s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5ca47a8dcb06ad584d01f12f18eee36a942159fd

 60%|█████▉    | 1839/3090 [2:48:39<3:39:46, 10.54s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b837abcb7504f61e51ff0e9fa449420502f945e9

 60%|█████▉    | 1840/3090 [2:48:43<3:00:23,  8.66s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2f5ec1b1e0da526f6d75bd1311267238dc3131a5

 60%|█████▉    | 1842/3090 [2:48:56<2:36:28,  7.52s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4a0db03cd946afccd3834cd01dca6350bb5afe16

 60%|█████▉    | 1847/3090 [2:49:35<2:29:46,  7.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0de7254fb42f09a0bfbc191c71553ab8278636a9

 60%|██████    | 1856/3090 [2:50:39<2:16:36,  6.64s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0cd765766d1911e02a5a414b5fa722ee63e56a60

 60%|██████    | 1858/3090 [2:50:50<2:02:45,  5.98s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/499ec33a370825d8558cf409255c60bcd2e4b4bb

 61%|██████    | 1871/3090 [2:52:24<2:15:42,  6.68s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a20252f32d2f8d1037619f1b0ddbb7da1c1e2927

 61%|██████    | 1888/3090 [2:54:10<1:38:48,  4.93s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 61%|██████    | 1889/3090 [2:54:14<1:35:31,  4.77s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 61%|██████    | 1890/3090 [2:54:18<1:30:20,  4.52s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/35875b700e12c83704c9de2059d7f92813634e35

 61%|██████    | 1891/3090 [2:54:21<1:24:29,  4.23s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 63%|██████▎   | 1944/3090 [2:59:01<1:38:49,  5.17s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1ba67d0ffce908ac9203917a7440ca1b86e08191

 63%|██████▎   | 1945/3090 [2:59:05<1:36:00,  5.03s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a328d89da1e92e1f5f9d36b7ee01003ba6ec677d

 63%|██████▎   | 1955/3090 [2:59:54<1:24:37,  4.47s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e2c5f4013b1d72464193b9ee21fc3b5660999172

 63%|██████▎   | 1956/3090 [2:59:59<1:25:15,  4.51s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d08524bc55df8e109168acbd65c80511df72941d

 63%|██████▎   | 1958/3090 [3:00:08<1:22:43,  4.38s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/24dd5d814dd7e3e9471154fb677e2da57dd31e57

 64%|██████▎   | 1967/3090 [3:00:52<1:27:04,  4.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/45504a51d82c98057cfa6d3f248267a9c74cf868

 64%|██████▍   | 1976/3090 [3:01:45<1:44:07,  5.61s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 64%|██████▍   | 1985/3090 [3:02:26<1:27:24,  4.75s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/cbc396283393d6fe244b93af6205859bfd468544

 65%|██████▍   | 1995/3090 [3:03:15<1:26:06,  4.72s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/94cd2f17eebd7b400e9aa9670cfc7ff467389b99

 65%|██████▍   | 1999/3090 [3:03:33<1:26:13,  4.74s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 65%|██████▌   | 2016/3090 [3:05:14<2:17:47,  7.70s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0a0f04bf85aca732af0354fdd19f7ecc25e0fabd

 66%|██████▌   | 2034/3090 [3:06:52<1:28:53,  5.05s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c3cb4d663a458fbdea9cca1cfe9caee7b29bddd6

 66%|██████▌   | 2035/3090 [3:06:57<1:30:07,  5.13s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/700f30d2e7e2747f5a966f620493aa54740be425

 66%|██████▌   | 2037/3090 [3:07:08<1:32:23,  5.26s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9f9b896956612de885ca68a0c9f3988018cca170

 66%|██████▌   | 2044/3090 [3:07:46<1:28:40,  5.09s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e27d8aaecccc50c85674fe64478fe3d34da13b01

 66%|██████▋   | 2049/3090 [3:08:10<1:28:29,  5.10s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/80d1e11b41cb4031c376ba7eb52c641a2e431c5e

 66%|██████▋   | 2052/3090 [3:08:24<1:22:14,  4.75s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5b90ec667d307141e64bd218925b71a91586b256

 67%|██████▋   | 2073/3090 [3:10:23<1:26:19,  5.09s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/01e75c2e98e29bae2cbddade2509246e0f9b2565

 67%|██████▋   | 2076/3090 [3:10:39<1:25:17,  5.05s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/81cfa7d59f25dcb95b4dde74dce69b6f5c420752

 67%|██████▋   | 2077/3090 [3:10:45<1:32:00,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4f2b0a2679d4ccbc4081a58688cb72ddee7544bd

 67%|██████▋   | 2082/3090 [3:11:14<1:34:52,  5.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/658b35e4ca474ead39a3683253c820022c76b1d0

 68%|██████▊   | 2093/3090 [3:12:15<1:33:50,  5.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e3fe896c726e715c828f8248841c5d56012f92be

 68%|██████▊   | 2098/3090 [3:12:43<1:35:43,  5.79s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ad590a81a92e24b3c812218ba09a14e9801afe79

 68%|██████▊   | 2105/3090 [3:13:21<1:25:36,  5.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ee32185dbda2f596c37cdb051fea34ab144812c9

 68%|██████▊   | 2116/3090 [3:14:20<1:25:12,  5.25s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/23b9c04a3b6953b5a404e10ab3a05a6b329ab41b

 69%|██████▊   | 2119/3090 [3:14:37<1:27:30,  5.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7db68104af6c2fb439808b0c6320c76d30cf780d

 69%|██████▊   | 2122/3090 [3:14:52<1:24:57,  5.27s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/474b94d1861a6d93b36b486d7bbf177d21dcdd42

 69%|██████▉   | 2136/3090 [3:16:06<1:16:33,  4.82s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dc08220b483bcbe72f09d342cf20bfc739ed540a

 70%|██████▉   | 2158/3090 [3:18:05<1:20:40,  5.19s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c2a3ac397b9c7e29c2c36452fde249dd5e22619d

 70%|███████   | 2166/3090 [3:18:50<1:25:44,  5.57s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7ff7bc526a2d8ca7f968dd52027439722fcd858f

 70%|███████   | 2167/3090 [3:18:55<1:22:38,  5.37s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 70%|███████   | 2171/3090 [3:19:19<1:32:14,  6.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/586177942353bcfebb13850ab27285d4451c5724

 70%|███████   | 2176/3090 [3:19:46<1:19:37,  5.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0a619eb6ef40fd1972f93e9391dcf227a7ea574f

 71%|███████   | 2195/3090 [3:21:29<1:22:52,  5.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6b5673010ce1b880da6708d7e48764e22902a0ab

 71%|███████   | 2198/3090 [3:21:46<1:22:06,  5.52s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b3860e4e7f78ec2d951cc2a5bd5a2c676f6aee18

 71%|███████▏  | 2202/3090 [3:22:07<1:16:17,  5.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4ce415d2a3a65bade15a663119832d06782157e0

 71%|███████▏  | 2205/3090 [3:22:23<1:17:49,  5.28s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7427d7a710902c7bcb908311fae111235115a317

 72%|███████▏  | 2216/3090 [3:23:23<1:20:08,  5.50s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a3c5f8341a04b4c9b41887a3711bed33e514f020

 72%|███████▏  | 2217/3090 [3:23:28<1:16:14,  5.24s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4c695c1b0d6a90dfe8068314c068f161013701d4

 72%|███████▏  | 2220/3090 [3:23:45<1:18:33,  5.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/34202bab12e82ec761cc86568bf8f46aad6597cf

 72%|███████▏  | 2225/3090 [3:24:13<1:18:53,  5.47s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6ed91b6252490a017666f4eb08d73148340d4114

 73%|███████▎  | 2241/3090 [3:25:45<1:18:40,  5.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/76a6a65b9ae771a3efdfea1c938f2322ad62ade8

 73%|███████▎  | 2244/3090 [3:26:00<1:13:47,  5.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/946bd441d114b140262f64b5790cdf68b1331356

 73%|███████▎  | 2264/3090 [3:27:50<1:09:20,  5.04s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/19d7a3aa0c277ffd8751c3e6e63c5a9203dfa142

 73%|███████▎  | 2265/3090 [3:27:55<1:08:13,  4.96s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4d21a358703a85dd59423054a7ba1b73adc1bd1a

 74%|███████▎  | 2277/3090 [3:29:02<1:09:18,  5.11s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b8b907109cb71b67d27109eed59b56963256f708

 74%|███████▍  | 2280/3090 [3:29:18<1:11:34,  5.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3794dc889799b7eef2c4bd60a91111d777f56a25

 74%|███████▍  | 2281/3090 [3:29:23<1:07:00,  4.97s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4b2ede28ec928708cbe0c6292c8fd96125761484

 74%|███████▍  | 2288/3090 [3:29:55<1:01:15,  4.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/04321d0c4eadb71a7ec48701d98cab69ba820d13

 74%|███████▍  | 2290/3090 [3:30:06<1:04:00,  4.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2ac6102dbad1f702a647c67fb02880158d52be17

 74%|███████▍  | 2296/3090 [3:30:36<1:06:28,  5.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/64960ad5b5ddea10e2c843541dba10ec6d8d0436

 74%|███████▍  | 2298/3090 [3:30:48<1:08:47,  5.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b519c3bb2c972e31d46d0d155cfefc1118544f6d

 75%|███████▍  | 2307/3090 [3:31:33<1:06:44,  5.11s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/312ae603a33335c9dfa1ba10981db76cfe0de1d4

 75%|███████▍  | 2308/3090 [3:31:38<1:05:49,  5.05s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e013e01ce8716958236946ac7bf9f1bd6a779077

 75%|███████▍  | 2309/3090 [3:31:45<1:11:46,  5.51s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 75%|███████▍  | 2310/3090 [3:31:50<1:11:14,  5.48s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e5bf5ec6f0015b7a51d9d434708bf4abf39b4607

 75%|███████▍  | 2317/3090 [3:32:28<1:08:36,  5.33s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/475daed80393f9c3a97e61081ebcc31c17977cf4

 75%|███████▌  | 2324/3090 [3:33:06<1:07:59,  5.33s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3a9d4fd37fe18cfbfcea4ff5805dc9f666427d2c

 76%|███████▌  | 2335/3090 [3:33:57<56:55,  4.52s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/59f4b4a4c0e275d625515e2f0447e337c9ecd24d

 76%|███████▌  | 2336/3090 [3:34:01<55:03,  4.38s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6ed60b406e472801db503d51f5df31c75276216e

 76%|███████▌  | 2340/3090 [3:34:19<55:59,  4.48s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a80849faa904d66396eef3a2392eeda711ec76eb

 76%|███████▌  | 2347/3090 [3:34:52<55:17,  4.46s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 76%|███████▌  | 2356/3090 [3:35:41<1:01:55,  5.06s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/527ca1d9d834437843e075281ccf3486e1fc8a08

 76%|███████▋  | 2357/3090 [3:35:44<57:18,  4.69s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/19b10203efd8e4f4a4cbb80ea7c4f24a72ec3f26

 76%|███████▋  | 2363/3090 [3:36:15<58:46,  4.85s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a095c2c3eb45924b35e6c81b46de10bfd9c4bbf0

 77%|███████▋  | 2368/3090 [3:36:41<1:04:20,  5.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d80e39a561c154f5bb7489ca41745b3773c13cf1

 77%|███████▋  | 2375/3090 [3:37:17<1:02:34,  5.25s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d18731d01c03fb1e7110c279f1841c73e599a6a8

 78%|███████▊  | 2399/3090 [3:39:26<51:39,  4.49s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b2bcb854562f6fdffc3e11242fb16de0a03da85c

 78%|███████▊  | 2400/3090 [3:39:30<49:55,  4.34s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e43667d7aaaa69e9f96cf01bebbe826d2ead7af9

 78%|███████▊  | 2401/3090 [3:39:34<48:12,  4.20s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/80b6de6d3b7e8f485668757d5503df9f50680198

 78%|███████▊  | 2418/3090 [3:40:54<54:12,  4.84s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/06f819696d7dcf8aa1d6387159d74122839316d4

 78%|███████▊  | 2422/3090 [3:41:14<54:55,  4.93s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4b2145c3cd211fa36d257816467806cb8eb2765d

 79%|███████▉  | 2436/3090 [3:42:38<56:07,  5.15s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2c00c82ede67da05736c99309f76a3d04ef33ddb

 79%|███████▉  | 2448/3090 [3:43:44<55:59,  5.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b92c825e2b8d8762c58ed18339344ec691214b8c

 79%|███████▉  | 2450/3090 [3:43:53<51:36,  4.84s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2e87df6f0d41a74b4fb37e0cfc755df5d4a27cc8

 80%|███████▉  | 2460/3090 [3:44:58<1:40:23,  9.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0b85b47bb6fb27714d732526f55eb0825caeddf0

 80%|███████▉  | 2461/3090 [3:45:03<1:25:24,  8.15s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ace4a0bacb3961fe00f3a5952ae720af272478d0

 80%|███████▉  | 2464/3090 [3:45:19<1:04:50,  6.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1b206ce26b6a7a8582024a44da2aad8d19193df2

 80%|███████▉  | 2470/3090 [3:45:47<52:05,  5.04s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/da95b94ed63f74e0af9f4347e343d4b399e75f4f

 80%|████████  | 2477/3090 [3:46:22<48:26,  4.74s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/43bb58659605d93f7463a109c486d3f91bf036cb

 80%|████████  | 2481/3090 [3:46:41<48:09,  4.74s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/66e4eae69f9728e286f7182c69265ccb3d6db96b

 80%|████████  | 2487/3090 [3:47:12<50:41,  5.04s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/db9b81d35070a4530e0ca9f36ffc12a47a1758a2

 81%|████████  | 2488/3090 [3:47:16<47:07,  4.70s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6c8c85a4f13e7e1b32e28427f1d0c03b9a57fef4

 81%|████████  | 2489/3090 [3:47:20<46:10,  4.61s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/47a02807fb1aac67cc952fca6f521906acaf8c1f

 81%|████████  | 2491/3090 [3:47:31<48:52,  4.90s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5838841a8058e1187f4dd06a67ab89f7e60920bf

 81%|████████  | 2494/3090 [3:47:46<49:55,  5.03s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 81%|████████  | 2496/3090 [3:47:56<49:20,  4.98s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6968fcf3698c6568a454ddf3c44819ae39601727

 81%|████████  | 2497/3090 [3:48:01<49:21,  4.99s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/23da9bfd72be60dedc3c508e4d12e8fb5387d78d

 81%|████████  | 2501/3090 [3:48:24<53:30,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e1698ebbd7436dd5c6deef90d4f3658956eba32f

 81%|████████  | 2502/3090 [3:48:28<50:00,  5.10s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7c4c4b7c3caba6fbf5e00cafd8e97387805d23fe

 81%|████████  | 2508/3090 [3:48:59<48:54,  5.04s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dc78183d77ab4c479bd98892a4d8b14be1eb4675

 81%|████████▏ | 2514/3090 [3:49:37<58:32,  6.10s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3407a2b19614e0f95597ed3cbc449590b57020fb

 81%|████████▏ | 2516/3090 [3:49:51<1:01:25,  6.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/65db50c2226be2bb72c88730b9248376107c9d26

 82%|████████▏ | 2522/3090 [3:50:27<57:18,  6.05s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d22ccd9f25171351ca86eafe1538aacf4fef1c36

 82%|████████▏ | 2524/3090 [3:50:40<55:59,  5.94s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b6960e4475add25ad42ecce2653f0d41dad48a0b

 82%|████████▏ | 2525/3090 [3:50:44<52:23,  5.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4e7f9ddbe20136837d97667b7095fb6c55c883e2

 82%|████████▏ | 2526/3090 [3:50:49<49:15,  5.24s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f14959f31b85fd9392a6ec0a73c93964499df02b

 82%|████████▏ | 2530/3090 [3:51:06<43:28,  4.66s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/654c384249a2f5d8f96825f6520842e179a27d01

 82%|████████▏ | 2531/3090 [3:51:11<42:08,  4.52s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/659a2727a2b1c1832ff5ae5bca69c8d7f7e6585c

 82%|████████▏ | 2536/3090 [3:51:38<48:06,  5.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c4b7c4a449aca9f3748f556e28a1d470d741bbde

 82%|████████▏ | 2537/3090 [3:51:43<47:29,  5.15s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/86461bfd52cfb9b7518ae58a7091ca51a7a24b11

 82%|████████▏ | 2538/3090 [3:51:48<46:02,  5.00s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/12c9bcf446abaffb28b24ea8e593725da209d2bf

 82%|████████▏ | 2541/3090 [3:52:02<43:58,  4.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f477e04664fa739bd3c90c1491f797e05e93f5f8

 82%|████████▏ | 2543/3090 [3:52:13<46:39,  5.12s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/61ce6a514e5ab9a8c8952790f55e75e709bbc93a

 82%|████████▏ | 2549/3090 [3:52:47<49:13,  5.46s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/da5b0299c7927315a151e77de4f976e01d77ef91

 83%|████████▎ | 2550/3090 [3:52:52<49:28,  5.50s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f890fa2b0f2b19fef1a0b08d5ea2831cec8213d7

 83%|████████▎ | 2551/3090 [3:52:58<49:17,  5.49s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/38db4d0d4747d8e70aa6aa23c89d964b2c44589b

 83%|████████▎ | 2553/3090 [3:53:11<54:05,  6.04s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3a441f4122c435572684e775e0b7203471f1e34d

 83%|████████▎ | 2560/3090 [3:53:44<40:03,  4.53s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/54d79ab0849c0609b57ac4dc045a6e9c2e5a3426

 83%|████████▎ | 2565/3090 [3:54:25<1:17:40,  8.88s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6754b65c0f288951827f150246e6cb656f06b65a

 83%|████████▎ | 2568/3090 [3:54:42<57:27,  6.60s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9b40e5cb81a4cc7361294683758df86a042fc76a

 83%|████████▎ | 2570/3090 [3:54:51<48:01,  5.54s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d02fa71628a96fbc69876b4a6ad8d6f8a0384973

 83%|████████▎ | 2572/3090 [3:54:59<42:11,  4.89s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2f5bc3fdac68b5e7f58865148fe39262baf671bc

 84%|████████▎ | 2581/3090 [3:55:55<45:59,  5.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d4ffa144d15092cb962abb208f7299d08ba32a6d

 84%|████████▎ | 2584/3090 [3:56:11<44:34,  5.29s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/637253ce3ac74d0bce38e68840f721ced236656a

 84%|████████▎ | 2586/3090 [3:56:21<42:05,  5.01s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f486b60191ef8c094b53a492bcd51797e3800c29

 84%|████████▍ | 2597/3090 [3:57:23<38:41,  4.71s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f2a31ac384ae0d58c5d993068330832ec29390f1

 84%|████████▍ | 2598/3090 [3:57:27<36:52,  4.50s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1a8623e8665566d06628d858b386dea43e20a0a1

 84%|████████▍ | 2599/3090 [3:57:31<35:21,  4.32s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c62b4186b6893a8993a0f32ca8d8f8d5ac5b37eb

 84%|████████▍ | 2601/3090 [3:57:42<39:50,  4.89s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d190e2a651dfd634302ad1930bb45832a23d8338

 84%|████████▍ | 2603/3090 [3:57:54<43:42,  5.39s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/55906b45a856dc7819d674ca3c77906ddf11beff

 84%|████████▍ | 2604/3090 [3:57:58<41:09,  5.08s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ac40bd3d92e1cf18250e5c64f3cf751133f9b404

 84%|████████▍ | 2608/3090 [3:58:20<42:37,  5.31s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d2aeb2d6bbd68d3755b2add58cba6c7aa2c924f1

 84%|████████▍ | 2609/3090 [3:58:23<38:38,  4.82s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/072ee7395715c2549b21e38c8fbc35b4cfc63ea2

 85%|████████▍ | 2612/3090 [3:58:38<39:35,  4.97s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/40ee709da954f40f68d6a9ed11e897e0fde909ad

 85%|████████▍ | 2625/3090 [3:59:47<36:23,  4.70s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/543188e0b486b4d5c4a0638e061888a6b88a9310

 85%|████████▍ | 2626/3090 [3:59:51<35:27,  4.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ef7591cd5c4cdd6c4c8ca453a05ad3e530a721f2

 85%|████████▌ | 2627/3090 [3:59:55<34:12,  4.43s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f02cc417e228ae9d7ca6a68a1218b249f2445773

 85%|████████▌ | 2630/3090 [4:00:13<39:44,  5.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/966a2ff0dcf161af93f0059b55ab4c0207dc9ec5

 85%|████████▌ | 2635/3090 [4:00:36<35:36,  4.70s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e40e4c101d89bfb17ff53b43952575ccf60e5a27

 85%|████████▌ | 2636/3090 [4:00:41<35:36,  4.71s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5d4fa18f95d981db4660385ffe7d5c3375917fc1

 85%|████████▌ | 2639/3090 [4:00:59<41:17,  5.49s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0f8a76b46e22d44de252bae0b70b53c9c55eb2d6

 86%|████████▌ | 2645/3090 [4:01:35<44:10,  5.96s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7551bb3e673ed4e6f3e3b852ca45b2070ea03f8f

 86%|████████▌ | 2652/3090 [4:02:15<40:24,  5.54s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6b76ef6f1637329756cb033288bcad7c6f016945

 86%|████████▌ | 2655/3090 [4:02:32<39:16,  5.42s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3446a23e07529bdf963dd5a66468ecc770543e6e

 86%|████████▌ | 2657/3090 [4:02:44<40:44,  5.64s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6c70227838f9e320d380c8237b8590c91b00ca20

 86%|████████▌ | 2658/3090 [4:02:48<37:33,  5.22s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/63629ba868996f39389768a45ec0c1edd1fb4ab2

 86%|████████▌ | 2665/3090 [4:03:29<37:55,  5.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/75a5c36ad38eaabaa239807e6fe3beb3e35164e5

 86%|████████▋ | 2669/3090 [4:03:56<44:44,  6.38s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/117ab8fd32adb39083716740220dd27263407477

 87%|████████▋ | 2676/3090 [4:04:46<48:29,  7.03s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f490dc989dace12bb36e0fa9fbe134109bf700e1

 87%|████████▋ | 2681/3090 [4:05:19<42:17,  6.20s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3359c1987f3b90d7250a8a3ec3748aee66a896e2

 87%|████████▋ | 2684/3090 [4:05:38<40:25,  5.97s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/30cc1450564631d71efaf8beb7a2dc462667c51a

 87%|████████▋ | 2691/3090 [4:06:22<46:22,  6.97s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3b9e8f32c7d22cff04d21e2bb85abaf2d2f3e9f6

 87%|████████▋ | 2692/3090 [4:06:26<41:12,  6.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a15aecaa943d9547cbe0a630cfa304bf251ae392

 87%|████████▋ | 2695/3090 [4:06:40<33:02,  5.02s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/582bbed4b288180384f63c05d74ee36771fcf457

 87%|████████▋ | 2703/3090 [4:07:25<35:28,  5.50s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3505f8ea69e2d2e4f68e07bf00b162ab502c979c

 88%|████████▊ | 2706/3090 [4:07:41<33:56,  5.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/114be850aaaadadc4afeb9f2b31722a0f9de2e6d

 88%|████████▊ | 2711/3090 [4:08:10<34:24,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/beb82c5d52cb76dff3cee46d5d5396e79c23694e

 88%|████████▊ | 2713/3090 [4:08:18<30:08,  4.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b8125691ca2e807dc54b86ec2573b61d43d44735

 88%|████████▊ | 2715/3090 [4:08:26<27:33,  4.41s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/552e56ad692e7b96e73bf527e586fa84878137b8

 88%|████████▊ | 2721/3090 [4:08:56<29:20,  4.77s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9c0c2b4b892e1ff13c47815427fbb1f04d7ebaf5

 88%|████████▊ | 2724/3090 [4:09:09<27:27,  4.50s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/44c2280c877aa87c94e8b5c557ec8142d4a06942

 88%|████████▊ | 2734/3090 [4:10:13<30:03,  5.07s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/797948d578a1feb91a07e3fedda64021aafa3956

 89%|████████▊ | 2736/3090 [4:10:22<27:41,  4.69s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1d517ee6c466ba2ca5eb51f2f116e456299fd4e9

 89%|████████▊ | 2740/3090 [4:10:41<27:28,  4.71s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7cc8dcf62578a3498c896b756fdcfcddae04c0a0

 89%|████████▊ | 2741/3090 [4:10:45<26:25,  4.54s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ebec09bc36fb828fc65037d590f903f1bc0ec4a7

 89%|████████▉ | 2747/3090 [4:11:16<29:32,  5.17s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/50d79032baae8f5fb59ee523a2afcc53b8fa51dc

 89%|████████▉ | 2763/3090 [4:12:43<24:43,  4.54s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9b5e9eec9967f51c18a610760016a704ceb967b8

 89%|████████▉ | 2764/3090 [4:12:47<25:05,  4.62s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f8874107eee644d6043e49c10c92d307eb25d3e4

 90%|████████▉ | 2771/3090 [4:13:30<30:57,  5.82s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6b5ab9adc0d2c1b26eb35add0441007f1177e2c3

 90%|█████████ | 2783/3090 [4:14:36<28:25,  5.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/0cbe29017d2a54104851be0570a635e0c560f612

 90%|█████████ | 2795/3090 [4:15:46<26:04,  5.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dc1d9ef7a119616af46371d54c38ce07de8147d1

 91%|█████████ | 2799/3090 [4:16:10<28:54,  5.96s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/ece549f0a85b89eb24404c87dd5e9b8831eb6603

 91%|█████████ | 2804/3090 [4:16:38<25:17,  5.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/82de3e258fcbd5064399de562c4c19bd268c62dc

 91%|█████████ | 2809/3090 [4:17:21<37:29,  8.00s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/47db353da48a84e07817f2ae00ec10cc7627bed7

 91%|█████████ | 2811/3090 [4:17:31<30:10,  6.49s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3030d08a758a289a87eb4eb6e99d3cdd79f3a4f5

 91%|█████████ | 2812/3090 [4:17:37<28:58,  6.25s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/884df898fdf141a3fe29b654aecd4be30177b7ce

 91%|█████████ | 2814/3090 [4:17:50<28:29,  6.19s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/18fc2aa116bf0d6a54eb658932146857ebe229cb

 91%|█████████▏| 2822/3090 [4:18:31<22:14,  4.98s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/59f4f48a0688ae14ff4061a0a0473c0e38722be1

 92%|█████████▏| 2831/3090 [4:19:19<22:22,  5.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2c1ed921a3dab96ea6204f666097c711ef097816

 92%|█████████▏| 2833/3090 [4:19:30<22:07,  5.17s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4b641e3b235bd59601228774d1d9fe0457881d0a

 92%|█████████▏| 2835/3090 [4:19:42<22:44,  5.35s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/87d2c402e203f74edbd28c56acfbc6957d7f3e6e

 92%|█████████▏| 2853/3090 [4:21:25<23:35,  5.97s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/67e9018a610320495392eed7d3cec022b8ad2a16

 92%|█████████▏| 2858/3090 [4:21:48<18:26,  4.77s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d058351114ccce850ea88a7d6b6e8bfe61f393e7

 93%|█████████▎| 2864/3090 [4:22:18<17:22,  4.61s/it]

[FAILED] API crawlers failed for DOI: https://ceur-ws.org/Vol-3799/abstract2GDE24.pdf

 93%|█████████▎| 2874/3090 [4:23:09<17:18,  4.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/707303b221d5936736411eb1190bc7bc6e032575

 93%|█████████▎| 2876/3090 [4:23:18<16:22,  4.59s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/aa8b2bcef1296a62639b57cb4f508c2a71f4d2a3

 93%|█████████▎| 2879/3090 [4:23:32<16:02,  4.56s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dd7c057ba0e2a201bf5466beaa2038d7cb965199

 93%|█████████▎| 2882/3090 [4:23:48<16:40,  4.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a64a25c5f8da9ef27b517ec4bbc5ec483cc57e47

 93%|█████████▎| 2885/3090 [4:24:06<18:46,  5.49s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1477683f0c3221f71945b1358609749f73f76581

 93%|█████████▎| 2887/3090 [4:24:18<18:55,  5.59s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/78bff35085520e0c8d89d3518d1fcfc907c70911

 93%|█████████▎| 2889/3090 [4:24:27<17:12,  5.14s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b44035b5551d06005c9c1a2d16743edec1e1800e

 94%|█████████▎| 2893/3090 [4:24:44<14:06,  4.29s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/03db4890c9eb70f226ed07a76d4b545a2c02aa19

 94%|█████████▎| 2894/3090 [4:24:48<13:56,  4.27s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6fb58d1d5b959b238ee5e87fa4666a126d4a68f3

 94%|█████████▍| 2901/3090 [4:25:23<15:11,  4.82s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/b6be6a0f73efd1b065babc82f6da3c4c107d66a1

 94%|█████████▍| 2904/3090 [4:25:36<14:02,  4.53s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d6d07aff758456f52fae02787bedffeb5e28562c

 94%|█████████▍| 2906/3090 [4:25:47<14:58,  4.88s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e2f233156bc8a4b6de43907da7b0bfa4774ecfe9

 94%|█████████▍| 2908/3090 [4:25:56<14:08,  4.66s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/10b763b31c054c5583e322c5d434e0ae077eff3d

 94%|█████████▍| 2910/3090 [4:26:10<16:47,  5.60s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f585119a003b2e77600a12c1d251e2ec8a7e0817

 94%|█████████▍| 2911/3090 [4:26:14<16:01,  5.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/7a8ba4a334239b39ee8564b0226383a89571bc0b

 95%|█████████▍| 2927/3090 [4:27:35<12:57,  4.77s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/6a2c93fd9503a3e741bc41ddf0920382f9764190

 95%|█████████▍| 2929/3090 [4:27:45<12:53,  4.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3a9ba92037043295e707da1f6e63af25819b3505

 95%|█████████▍| 2931/3090 [4:27:53<11:24,  4.31s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/187ba70179288e8761f143fe84508fc17e727889

 95%|█████████▍| 2933/3090 [4:27:59<09:57,  3.80s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e15e21702a1938a89cb4b394638f129d97e0059a

 95%|█████████▍| 2935/3090 [4:28:09<11:01,  4.27s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4640ed868e9011164c9dd94ad9883e2529180e1a

 95%|█████████▌| 2942/3090 [4:28:48<12:05,  4.90s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c4e353d3a8a60bb9f8bd0a253b8b87f77cbc91e4

 95%|█████████▌| 2943/3090 [4:28:53<11:38,  4.75s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dc1fba9fabd4a2d5531b7b74d12c073ce407f2db

 95%|█████████▌| 2944/3090 [4:28:56<10:51,  4.46s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dde823250145eaa040eabba281fa4b396d6cdb30

 96%|█████████▌| 2956/3090 [4:29:58<11:56,  5.34s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/33c35cf64b96e65a8817b8329f381f14925513c9

 96%|█████████▌| 2962/3090 [4:30:29<10:41,  5.01s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2295fa704e385be89d8090cd5fa67bef316ba764

 96%|█████████▌| 2964/3090 [4:30:40<10:15,  4.89s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/aa422e448b4f532829a639f5b787000b149a56db

 96%|█████████▋| 2975/3090 [4:31:36<10:26,  5.45s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/cdb423d6f769a9a171fb6da8fba715fc792393d5

 96%|█████████▋| 2976/3090 [4:31:40<09:25,  4.96s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/46596f682911bfc1c109582041583c7bd75010a3

 97%|█████████▋| 2988/3090 [4:32:41<08:14,  4.85s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/cc28f2744a8ab728ad6cb59d53ebdfce855b268b

 97%|█████████▋| 2990/3090 [4:32:51<08:00,  4.81s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e53955f28dbb9768592cbc5575e8fe0621cf0bbf

 97%|█████████▋| 2995/3090 [4:33:16<07:42,  4.87s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a2a797cdd378fd88b2f63d3ee031c704f4558ab4

 97%|█████████▋| 2996/3090 [4:33:21<07:39,  4.88s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/cd0bf4a6fabfb4a898e957e7a20da49dc97f053a

 97%|█████████▋| 2999/3090 [4:33:34<06:48,  4.49s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/079b2cc0f7d0e94d41703b47bff0f82c3cda6052

 97%|█████████▋| 3002/3090 [4:33:46<06:11,  4.23s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/2d17d63001f0a4502d7df8f00c77c38914cf1c75

 97%|█████████▋| 3004/3090 [4:33:57<06:55,  4.84s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/3e5606525682b9be8f9741899dfe63f1ebff49d6

 97%|█████████▋| 3005/3090 [4:34:02<06:55,  4.89s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/a34df843e5ffc451a42fd6781316fbe5567b75a5

 98%|█████████▊| 3013/3090 [4:34:41<05:30,  4.30s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/c429cde90f6371d35f3f4582aa4a4555168f0a30

 98%|█████████▊| 3025/3090 [4:35:55<05:01,  4.63s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/cd8ff464d7905f6dc849b2782f98750297d1dad9

 98%|█████████▊| 3028/3090 [4:36:10<05:13,  5.05s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/308f866fd518103cdaa7ad2611484fd84fab8579

 98%|█████████▊| 3036/3090 [4:36:46<03:49,  4.25s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/84078b822bd5a05cb5b2fc4b4588e993cfd7077e

 99%|█████████▊| 3049/3090 [4:37:57<03:34,  5.22s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/569ce9577c959ece18c1d7c9a8420cc18e3ec2d4

 99%|█████████▊| 3050/3090 [4:38:01<03:16,  4.92s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/77e6d0966546ed7eb3a1e66af5068118a761efef

 99%|█████████▉| 3053/3090 [4:38:14<02:41,  4.37s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e6591854a3047fe45fd8040e89c85c0fd967e1be

 99%|█████████▉| 3055/3090 [4:38:23<02:34,  4.40s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e8bd1f4241098e543af4191534494e114febcb55

 99%|█████████▉| 3056/3090 [4:38:27<02:23,  4.21s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/5e2435bf388da8b8d40f07f4f74f5934ece9ec11

 99%|█████████▉| 3057/3090 [4:38:30<02:15,  4.11s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/074cd832221630a680b9e4d1363faf64b4034ba8

 99%|█████████▉| 3067/3090 [4:39:28<02:02,  5.32s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/dc650041838b505357e4a72d7ef269660d28101a

 99%|█████████▉| 3074/3090 [4:39:57<01:06,  4.18s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/e50e69c314fd40210e1731b1a34edaf16482c9ac

100%|█████████▉| 3075/3090 [4:40:01<01:03,  4.24s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/99d15b4c9b95600675c11fb287e63850fd2cc133

100%|█████████▉| 3077/3090 [4:40:11<01:00,  4.65s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/60347869db7d1940958ee465b3010b3a612bf791

100%|█████████▉| 3079/3090 [4:40:21<00:51,  4.71s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/f64893468ae17a1f244219e6b59424210f038c8b

100%|█████████▉| 3081/3090 [4:40:33<00:46,  5.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/58e504fab204e227e241d5c33a5f9baaa382e843

100%|█████████▉| 3083/3090 [4:40:41<00:32,  4.58s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/d79da1ef6ba583f9eed3c92eac51cc987c6a3187

100%|█████████▉| 3085/3090 [4:40:53<00:25,  5.16s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/4ebc684ba953213c60f4bb88ece4958ae2445c13

100%|█████████▉| 3086/3090 [4:40:57<00:19,  4.86s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/1918b04f40f0066161c96bb1af34dd95d58e2fc1

100%|█████████▉| 3087/3090 [4:41:01<00:13,  4.50s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/9c5f3c0ff283249fe91960e8d9a772b53311a068

100%|██████████| 3090/3090 [4:41:15<00:00,  5.46s/it]

[FAILED] API crawlers failed for DOI: https://www.semanticscholar.org/paper/58f90effcca0067d762fe06ad9a3de3d8e0d1ba3
===== CRAWL DONE =====
Total crawled: 2448

In [6]:
print("===== SAVE GLOBAL CRAWL DATA =====")

crawl_df = pd.DataFrame(crawl_results)

print("Shape:", crawl_df.shape)
display(crawl_df.head())

save_csv(crawl_df, CRAWLED_ABSTRACT_PATH)

print("Saved to:", CRAWLED_ABSTRACT_PATH)

===== SAVE GLOBAL CRAWL DATA =====
Shape: (2448, 6)

,id,doi,abstract,crawled_authors,source,authors
0,1,10.3389/fnbot.2013.00021,Gradient boosting machines are a family of pow...,"Alexey Natekin, Alois Knoll",SemanticScholarPaperIDCrawler,NaN
1,2,https://www.semanticscholar.org/paper/1c433ff0...,Our goal in this article is to remind readers ...,"Eve Tuck, K. Wayne Yang",SemanticScholarPaperIDCrawler,NaN
2,5,10.5281/zenodo.17571635,The rapid growth of Deep Neural Networks (DNNs...,"Baroni, Pietro, Cerutti, Federico, Giacomin, M...",SemanticScholarPaperIDCrawler,NaN
3,7,10.1109/tmi.2014.2377694,In this paper we report the set-up and results...,"Bjoern Menze, András Jakab, Stefan Bauer, Jaya...",SemanticScholarPaperIDCrawler,NaN
4,8,https://www.semanticscholar.org/paper/7d8de01e...,"Henry Jenkins, Director of the Comparative Med...",Henry Jenkins,SemanticScholarPaperIDCrawler,NaN

Saved CSV -> /Users/nhatnam/Documents/DM_252/Assignment/data/external/crawled_abstracts.csv
Saved to: /Users/nhatnam/Documents/DM_252/Assignment/data/external/crawled_abstracts.csv

In [ ]:
print("===== MERGE TRAIN + TEST WITH CRAWLED DATA =====")

import pandas as pd
from tqdm import tqdm

from src.config import (
    TRAIN_PATH_STAGE1,
    TEST_PATH_STAGE1,
    CRAWLED_ABSTRACT_PATH
)

from src.preprocess.merge_data import DataMerger
from src.config import DataPaths, BASE_DIR

# =========================
# INIT PATHS
# =========================
paths = DataPaths(BASE_DIR)

# =========================
# LOAD DATA
# =========================
train_df = pd.read_csv(TRAIN_PATH_STAGE1)
test_df = pd.read_csv(TEST_PATH_STAGE1)
crawl_df = pd.read_csv(CRAWLED_ABSTRACT_PATH)

print("Train:", train_df.shape)
print("Test:", test_df.shape)
print("Crawled:", crawl_df.shape)

# =========================
# MERGE
# =========================
merger = DataMerger()

print("Merging train...")
train_merged = merger.transform(train_df, crawl_df)

print("Merging test...")
test_merged = merger.transform(test_df, crawl_df)

# =========================
# SAVE INTERIM
# =========================
train_merged.to_csv(paths.merged_train, index=False)
test_merged.to_csv(paths.merged_test, index=False)

print("===== DONE =====")
print("Saved:")
print(" -", paths.merged_train)
print(" -", paths.merged_test)

===== MERGE TRAIN + TEST WITH CRAWLED DATA =====

ModuleNotFoundError: No module named 'src.preprocess.merge_data'