    Test crawl DOI

In [1]:
import sys
from pathlib import Path
import pandas as pd
from tqdm import tqdm

# Add project root to Python path
PROJECT_ROOT = Path("../").resolve()
sys.path.append(str(PROJECT_ROOT))

from src.config import TRAIN_PATH_STAGE1, TEST_PATH_STAGE1, CRAWLED_ABSTRACT_PATH
from src.utils.utils import load_csv, save_csv
from src.crawler.fallback_crawler import FallbackCrawler

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
print("===== LOAD DATA =====")

train_df = load_csv(TRAIN_PATH_STAGE1)
test_df = load_csv(TEST_PATH_STAGE1)

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

print("\n===== COLUMNS =====")
print("Train columns:", list(train_df.columns))
print("Test columns:", list(test_df.columns))

display(train_df.head(3))
display(test_df.head(3))

===== LOAD DATA =====
Train shape: (510, 7)
Test shape: (86, 6)

===== COLUMNS =====
Train columns: ['title', 'venue', 'year', 'authors', 'doi', 'Label', 'id']
Test columns: ['title', 'venue', 'year', 'authors', 'doi', 'id']

,title,venue,year,authors,doi,Label,id
0,Tabled CLP for Reasoning Over Stream Data.,iclp,2016,"Edmond Jajaga, Lule Ahmedi",10.1109/icsc.2017.64,1,299
1,XAI-LAW: A Logic Programming Tool for Modeling...,iclp,2025,"Agostino Dovier, Talissa Dreossi, Andrea Formi...",10.4204/eptcs.439.28,5,92
2,Workshop Proceedings of the 40th International...,iclp,2024,"Esteban Guerrero, Juan Carlos Nieves",10.1007/978-3-031-74209-5_21,1,311

,title,venue,year,authors,doi,id
0,Research Summary on Implementing Functional Pa...,iclp,2020,Finn Teegen,10.4204/eptcs.325.39,498
1,Reasoning in Highly Reactive Environments.,iclp,2019,Francesco Pacenza,10.4204/eptcs.306.57,255
2,Logic Programming with Max-Clique and its Appl...,iclp,2017,"Igor Dukanovic, Franz Rendl",10.1007/s10107-006-0026-z,570

In [3]:
print("===== INIT CRAWLER =====")

crawler = FallbackCrawler(timeout=30)

print("Crawler initialized successfully.")

===== INIT CRAWLER =====
Crawler initialized successfully.

In [4]:
print("===== PREPARE CRAWL STORAGE =====")

crawl_results = []

print("Train size:", len(train_df))
print("Test size:", len(test_df))

sample_doi = train_df.iloc[0]["doi"]
sample_id = train_df.iloc[0]["id"]

print("Sample DOI:", sample_doi)
print("Sample ID:", sample_id)

===== PREPARE CRAWL STORAGE =====
Train size: 510
Test size: 86
Sample DOI: 10.1109/icsc.2017.64
Sample ID: 299

In [5]:
print("===== MERGE TRAIN + TEST FOR CRAWLING =====")

all_df = pd.concat([train_df, test_df], axis=0)

print("Total to crawl:", len(all_df))

crawl_results = []

for idx, row in tqdm(all_df.iterrows(), total=len(all_df)):
    doi = row["doi"]
    paper_id = row["id"]

    try:
        result = crawler.fetch_by_doi(
            doi=doi,
            paper_id=paper_id
        )

        if result:
            crawl_results.append(result)

    except Exception as e:
        print(f"[ERROR] id={paper_id} | {str(e)}")

print("===== CRAWL DONE =====")
print("Total crawled:", len(crawl_results))

===== MERGE TRAIN + TEST FOR CRAWLING =====
Total to crawl: 596

  2%|▏         | 10/596 [00:14<13:16,  1.36s/it]

[FAILED] API crawlers failed for DOI: 10.1016/s0092-4563(08)36021-8

  3%|▎         | 17/596 [00:25<16:48,  1.74s/it]

[FAILED] API crawlers failed for DOI: 10.1016/s0167-9236(01)00138-5

  4%|▎         | 21/596 [00:33<19:53,  2.08s/it]

[FAILED] API crawlers failed for DOI: 10.1108/k.2000.06729iae.003

  5%|▍         | 28/596 [00:40<12:19,  1.30s/it]

[FAILED] API crawlers failed for DOI: 10.7551/mitpress/4307.003.0022

  5%|▍         | 29/596 [00:43<16:03,  1.70s/it]

[FAILED] API crawlers failed for DOI: 10.1109/tits.2024.3510515/mm1

  5%|▌         | 30/596 [00:47<24:16,  2.57s/it]

[FAILED] API crawlers failed for DOI: 10.1002/eng2.70433/v1/review2

  5%|▌         | 31/596 [00:50<25:17,  2.69s/it]

[FAILED] API crawlers failed for DOI: 10.1017/cbo9781107257115.023

  8%|▊         | 49/596 [01:08<18:09,  1.99s/it]

[FAILED] API crawlers failed for DOI: 10.1484/m.art-eb.5.138353

 10%|▉         | 58/596 [01:16<11:39,  1.30s/it]

[FAILED] API crawlers failed for DOI: 10.1016/0304-3975(88)90037-0

 10%|▉         | 59/596 [01:18<14:15,  1.59s/it]

[FAILED] API crawlers failed for DOI: 10.1109/tse.2025.3569086/mm1

 11%|█▏        | 68/596 [01:28<13:58,  1.59s/it]

[FAILED] API crawlers failed for DOI: 10.1088/2632-2153/ae2381/data7

 15%|█▌        | 90/596 [01:52<11:51,  1.41s/it]

[FAILED] API crawlers failed for DOI: 10.1017/cbo9780511814105.011

 17%|█▋        | 101/596 [02:11<24:03,  2.92s/it]

[FAILED] API crawlers failed for DOI: 10.4204/eptcs.439.14

 23%|██▎       | 135/596 [02:46<09:29,  1.24s/it]

[FAILED] API crawlers failed for DOI: 10.21236/ada208322

 27%|██▋       | 162/596 [03:11<08:07,  1.12s/it]

[FAILED] API crawlers failed for DOI: 10.1109/cscc49995.2020.00008

 31%|███       | 183/596 [03:36<11:35,  1.68s/it]

[FAILED] API crawlers failed for DOI: 10.18356/7a3e9edf-en

 31%|███       | 186/596 [04:04<57:03,  8.35s/it]

[FAILED] API crawlers failed for DOI: 10.1057/9781137476180.0009

 32%|███▏      | 192/596 [04:12<16:23,  2.43s/it]

[FAILED] API crawlers failed for DOI: 10.1016/b978-044450228-5/50016-3

 32%|███▏      | 193/596 [04:15<17:12,  2.56s/it]

[FAILED] API crawlers failed for DOI: 10.32614/cran.package.rswipl

 38%|███▊      | 224/596 [04:48<07:33,  1.22s/it]

[FAILED] API crawlers failed for DOI: 10.1484/m.art-eb.5.138353

 38%|███▊      | 228/596 [04:56<10:04,  1.64s/it]

[FAILED] API crawlers failed for DOI: 10.12968/prtu.2012.1.4.38

 39%|███▉      | 234/596 [05:09<15:49,  2.62s/it]

[FAILED] API crawlers failed for DOI: 10.1098/rsos.230785/v1/review1

 40%|████      | 240/596 [05:24<14:14,  2.40s/it]

[FAILED] API crawlers failed for DOI: 10.4204/eptcs.306.6

 42%|████▏     | 253/596 [05:50<15:27,  2.70s/it]

[FAILED] API crawlers failed for DOI: 10.5220/0006518303670372

 43%|████▎     | 254/596 [05:52<15:10,  2.66s/it]

[FAILED] API crawlers failed for DOI: 10.1016/j.jfma.2025.09.032

 43%|████▎     | 258/596 [06:02<15:07,  2.68s/it]

[FAILED] API crawlers failed for DOI: 10.1016/b978-0-934613-04-0.50007-7

 47%|████▋     | 278/596 [06:38<12:46,  2.41s/it]

[FAILED] API crawlers failed for DOI: 10.1098/rsos.230785/v1/review1

 52%|█████▏    | 308/596 [07:13<06:29,  1.35s/it]

[FAILED] API crawlers failed for DOI: 10.1016/b978-0-12-801416-5.09988-5

 56%|█████▌    | 331/596 [07:50<09:51,  2.23s/it]

[FAILED] API crawlers failed for DOI: 10.7551/mitpress/4304.003.0016

 59%|█████▉    | 352/596 [08:12<06:17,  1.55s/it]

[FAILED] API crawlers failed for DOI: 10.7551/mitpress/2123.003.0002

 62%|██████▏   | 369/596 [08:34<09:29,  2.51s/it]

[FAILED] API crawlers failed for DOI: 10.4204/eptcs.364.22

 62%|██████▏   | 372/596 [08:37<06:45,  1.81s/it]

[FAILED] API crawlers failed for DOI: 10.1016/b978-1-4832-1452-8.50157-3

 63%|██████▎   | 374/596 [08:40<06:04,  1.64s/it]

[FAILED] API crawlers failed for DOI: 10.1097/00152258-200701000-00006

 63%|██████▎   | 378/596 [08:45<06:19,  1.74s/it]

[FAILED] API crawlers failed for DOI: 10.1016/j.radphyschem.2026.113646

 66%|██████▋   | 396/596 [09:04<06:55,  2.08s/it]

[FAILED] API crawlers failed for DOI: 10.1016/s0004-3702(02)00186-8

 67%|██████▋   | 397/596 [09:06<06:38,  2.00s/it]

[FAILED] API crawlers failed for DOI: 10.1484/m.hmantica-eb.5.152373

 71%|███████   | 421/596 [09:29<03:06,  1.07s/it]

[FAILED] API crawlers failed for DOI: 10.1037/e580582009-009

 71%|███████   | 424/596 [09:33<03:57,  1.38s/it]

[FAILED] API crawlers failed for DOI: 10.1017/9781009003797.008

 73%|███████▎  | 435/596 [10:14<21:14,  7.91s/it]

[FAILED] API crawlers failed for DOI: 10.14711/thesis-b1584877

 79%|███████▉  | 472/596 [10:57<02:15,  1.10s/it]

[FAILED] API crawlers failed for DOI: 10.2139/ssrn.4850544

 82%|████████▏ | 489/596 [11:32<05:15,  2.94s/it]

[FAILED] API crawlers failed for DOI: 10.5220/0009093407580765

 85%|████████▌ | 508/596 [12:01<02:13,  1.52s/it]

[FAILED] API crawlers failed for DOI: 10.1002/9781394388660.ch3

 90%|█████████ | 539/596 [12:54<01:58,  2.08s/it]

[FAILED] API crawlers failed for DOI: 10.1007/978-3-540-74610-2

 91%|█████████ | 542/596 [12:58<01:22,  1.53s/it]

[FAILED] API crawlers failed for DOI: 10.7551/mitpress/4316.003.0033

 93%|█████████▎| 552/596 [13:07<00:54,  1.23s/it]

[FAILED] API crawlers failed for DOI: 10.2307/jj.30297486.9

 94%|█████████▍| 559/596 [13:14<00:56,  1.54s/it]

[FAILED] API crawlers failed for DOI: 10.4204/eptcs.364.24

 94%|█████████▍| 563/596 [13:20<00:56,  1.71s/it]

[FAILED] API crawlers failed for DOI: 10.1016/b978-1-4832-1452-8.50151-2

 95%|█████████▍| 564/596 [13:22<00:56,  1.76s/it]

[FAILED] API crawlers failed for DOI: 10.1126/science.1662-b

 95%|█████████▌| 567/596 [13:25<00:41,  1.42s/it]

[FAILED] API crawlers failed for DOI: 10.1002/seup.v12:1

 96%|█████████▋| 575/596 [13:36<00:30,  1.46s/it]

[FAILED] API crawlers failed for DOI: 10.1145/3291621

 97%|█████████▋| 580/596 [13:45<00:28,  1.77s/it]

[FAILED] API crawlers failed for DOI: 10.4204/eptcs.345.10

 98%|█████████▊| 584/596 [13:53<00:25,  2.09s/it]

[FAILED] API crawlers failed for DOI: 10.1016/s0743-1066(00)00004-2

 98%|█████████▊| 587/596 [14:02<00:28,  3.12s/it]

[FAILED] API crawlers failed for DOI: 10.5220/0005824305320539

100%|██████████| 596/596 [14:14<00:00,  1.43s/it]

===== CRAWL DONE =====
Total crawled: 543

In [16]:
import pandas as pd
import re
import numpy as np

print("===== STRONG CLEAN CRAWL RESULTS =====")

crawl_df = pd.DataFrame(crawl_results)

def deep_clean(x):
    if x is None:
        return ""
    
    if isinstance(x, float) and np.isnan(x):
        return ""
    
    x = str(x)

    x = x.replace("\r\n", " ")
    x = x.replace("\n", " ")
    x = x.replace("\r", " ")
    x = x.replace("¶", " ")
    x = x.replace("\u00b6", "")

    x = x.replace("\t", " ")

    x = re.sub(r"\s+", " ", x)

    return x.strip()

for col in crawl_df.columns:
    crawl_df[col] = crawl_df[col].apply(deep_clean)

===== STRONG CLEAN CRAWL RESULTS =====

In [17]:
print("===== SAVE GLOBAL CRAWL DATA =====")

crawl_df = pd.DataFrame(crawl_results)

print("Shape:", crawl_df.shape)
display(crawl_df.head())

save_csv(crawl_df, CRAWLED_ABSTRACT_PATH)

print("Saved to:", CRAWLED_ABSTRACT_PATH)

===== SAVE GLOBAL CRAWL DATA =====
Shape: (543, 5)

,id,doi,abstract,crawled_authors,source
0,299,10.1109/icsc.2017.64,Semantic technologies have been extensively us...,"Edmond Jajaga, Lule Ahmedi",OpenAlexCrawler
1,92,10.4204/eptcs.439.28,We propose an approach to model articles of th...,"A. Dovier, Talissa Dreossi, A. Formisano, Bene...",SemanticScholarCrawler
2,311,10.1007/978-3-031-74209-5_21,"Traditionally, in the argumentation theory lit...",,DOIResolverCrawler
3,136,10.24963/kr.2025/85,"In multi-agent environments, effective interac...","Chenyuan Zhang, Cristian Rojas Cardenas, Hamid...",CrossRefCrawler
4,41,10.24963/kr.2024/32,Multi-agent epistemic planning (MEP) is about ...,"Biqing Fang, Fangzhen Lin",SemanticScholarCrawler

Saved CSV -> /Users/nhatnam/Documents/DM_252/Assignment/data/external/crawled_abstracts.csv
Saved to: /Users/nhatnam/Documents/DM_252/Assignment/data/external/crawled_abstracts.csv